### ISSUE TITLE
Remove "update file" from FileSet show page

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#1091]
It doesn't work.

**Comment by christinach** [comment]
![filemanagerupdate](https://user-images.githubusercontent.com/9905193/39011708-3f7f8fa8-43e0-11e8-92c7-f2163a8ed458.png)

**Comment by escowles** [comment]
Maybe we should fix uploads?  Or is there another way to upload files, so we could just get rid of this?

**Comment by tpendragon** [comment]
Updating these files works for me, but it doesn't do things like regenerate derivatives given the new source file. I think we should ditch this use case as nobody does it - if there's a problem they're likely to just upload a new file via browse everything rather than replace the file in place right?

**Comment by escowles** [comment]
I'm fine with removing them — I agree that nobody uses them, and I would expect users to just upload a new page using BrowseEverything instead.
