### ISSUE TITLE
What are the tradeoffs of using different backends?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#11]
* Which are the best backends to use in development, local test, CI, production, etc.?
* To what extent do we depend on the differences?
* Should Valkyrie be more explicit about what backends provide what features?

**Comment by tpendragon** [comment]
I ran some performance tests, and for small numbers of objects the difference in spec performance between postgres and in-memory is marginal (they both vary 1 or 2 seconds faster/slower than the other, depending on who knows what)

**Comment by tpendragon** [comment]
2. I want to depend on transactions. The Data Mapper WG has talked about transaction support in the past, but avoided it largely because only some backends can do it, so we'd have to find a pattern for advertising that support.

3. I think right now, because of above, they all support the same things for each adapter. Being explicit would mean solving the "optional" features piece.
