### ISSUE TITLE
Don't re-ingest duplicates, but don't use content-addressable storage.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#118]

**Comment by tpendragon** [comment]
I don't think this is possible without a `find_by_checksum` query.

**Comment by escowles** [comment]
I think it would be good to talk to the Data Mapper WG about this — both specifically `find_by_checksum` since identifying duplicate files seems like functionality many people would want, but also more generally, how we might provide for different functionality in different backends.

This is another case where some backends could easily implement some functionality, but Fedora cannot.  Should we create a shared spec for queryable backends?  Should we just add flags for each of these queries so it's clear in the specs which features different backends support?

**Comment by tpendragon** [comment]
I think find_by_checksum is pretty implementable across all the adapters if we want to add that - the thing that makes it more complicated is we store checksums as part of a nested object, so we'd either have to stop that or standardize on it.

**Comment by tpendragon** [comment]
This ship has sailed I think.
