### ISSUE TITLE
HTML5 Player for the access files of a MediaResource

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1226]

**Comment by jrgriffiniii** [comment]
No decisions have been made regarding the identification of a player, an HTML5 player may be sufficient.

**Comment by jrgriffiniii** [comment]
Concerns and questions regarding a IIIF 3.0 compliant player should inform this decision.  For the moment, a HTML5 should be sufficient.

**Comment by sdellis** [comment]
Will all manifests suddenly go from v2 to v3? UV will support v3, but unfortunately it doesn't use the context object to determine which version it is or which functions to call. I think this should be addressed in the UV collaborative sprint so that it knows, for example, to use getItems() on a v3 Canvas when getImages() is called.

**Comment by jrgriffiniii** [comment]
[cjcolvar](https://github.com/cjcolvar) has been fairly diligent about addressing early IIIF 3.0 support upstream (https://github.com/samvera-labs/iiif_manifest/pull/19), so we should be in the position to identify to any server-side structural issues which prevent UV from consuming responses.

**Comment by sdellis** [comment]
Sorry, I meant Manifesto above... so my comment may not be relevant to this issue. UV currently supports v3, with a couple exceptions like requiredStatement and rights.
