### ISSUE TITLE
Explore IIIF 3.0 Migration Support

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#1364]
Discuss with community members how to support publishing IIIF Manifests between versions for different viewers.

**Comment by tpendragon** [comment]
UV gotcha:

IIIF image `service` declarations have to have an `@id` and `@type` key rather than `id` and `type`, and the `profile` has to be `http://iiif.io/api/image/2/level2.json`. `@type` should be `ImageService2`.

You can find an example v3 manifest here: https://d.lib.ncsu.edu/collections/catalog/nubian-message-2003-04-01/manifest?v3=true
