### ISSUE TITLE
Ephemera: Save and Duplicate Metadata not working

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1457]

**Comment by jrgriffiniii** [comment]
The controller action and parameters appear to be properly set, but when attempting to "save" a new resource with duplicated metadata, the HTTP method used is `POST` rather than `PATCH` (the latter also doesn't specify an ID for the resource, as it is new, and hence, a routing error is raised).

**Comment by jrgriffiniii** [comment]
For further clarification:
```
> params
<ActionController::Parameters {"create_another"=>"5cce556c-dbfd-4a39-ac33-1525681da244", "controller"=>"ephemera_folders", "action"=>"new", "parent_id"=>"fb2c2207-61c0-4186-885c-b50df3eec53f"} permitted: false>

> simple_form_for @change_set do |f| ; nil end
<form class="simple_form edit_ephemera_folder" id="edit_ephemera_folder_" action="/concern/ephemera_folders/" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="_method" value="patch" /></form>

```

**Comment by jrgriffiniii** [comment]
The `patch` method is appended by `ActionView::Helpers::FormHelper` for `<form>` tags generated by `SimpleForm`.

This is due to the fact that "Save and Duplicate Metadata" creates and a new resource in the `EphemeraFolderChangeSet` which falsely indicates that it has been persisted:
```
[7] pry(#<#<Class:0x00007faefee8b070>>)> record.class
=> BoxlessEphemeraFolderChangeSet
[8] pry(#<#<Class:0x00007faefee8b070>>)> record.model.class
=> EphemeraFolder
[9] pry(#<#<Class:0x00007faefee8b070>>)> record.model.persisted?
=> true
[10] pry(#<#<Class:0x00007faefee8b070>>)> record.model.id
=> nil
```

`FormHelper` checks to determine whether or not the model was persisted, and if it has been, appends the `patch` method:
https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_helper.rb#L1524
