### ISSUE TITLE
Require users to be logged in to search?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#150]
We don't want users to use Plum/Figgy for discovery, but manifests need to be public for use in other applications.

**Comment by tpendragon** [comment]
Is this important? Why do we care if people can search?

**Comment by escowles** [comment]
I don't think this is important — the content is available as manifests, so there's no access control aspect to this.  But this would discourage linking to Plum instead of OL/DPUL/etc.

**Comment by jpstroop** [comment]
Add to agenda for Friday?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

On Aug 31, 2017 12:11 PM, "Esmé Cowles" <notifications@github.com> wrote:

I don't think this is important — the content is available as manifests, so
there's no access control aspect to this. But this would discourage linking
to Plum instead of OL/DPUL/etc.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pulibrary/figgy/issues/150#issuecomment-326345762>, or mute
the thread
