### ISSUE TITLE
Improve Bulk Ingest Efficiency for Large Books

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1536]
Also want to bulk ingest, e.g. 5 books
Need folder selector; browse_everything only provides file-level selection. Want just the name of the folder.

discussed at digital studio users meeting 7/19/2018

**Comment by tpendragon** [comment]
This works now, but not for really large books.

Problem: Our bulk ingest interface uses Browse Everything to select the parent folder. When you select the parent folder, it then iterates through every child folder/file and selects them. The controller then calculates what the parent is from the list of files that is sent. If there are several thousand files, then it takes a ridiculously long time for the JS to select them all.

Rather than selecting files, we should be selecting folders.

**Comment by hackmastera** [comment]
discussed 1/14/19

**Comment by jrgriffiniii** [comment]
Users should be able to select a parent directory without automatically selecting all file entries within it.
