### ISSUE TITLE
Ingest "Wilson" (pudl0048)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1593]
These don't appear to be ingested anywhere. Migrate?

Ping @jpstroop @joycebcat

**Comment by escowles** [comment]
Needs metadata.

**Comment by jpstroop** [comment]
I believe this was copied over to MC215, e.g. https://findingaids.princeton.edu/collections/MC215/c002. If that's a match we can ingest using the PULFA-flavored METS.

**Comment by cwulfman** [comment]
A very early project to digitize the content of the Woodrow Wilson Additional Papers (MC215), held within the Public Policy Papers at Mudd Manuscript Library in order to make these materials available to the public via the web and to explore how best to digitize archival materials and archival collections.  

Already migrated: https://figgy.princeton.edu/catalog/454e0459-8808-43fd-a6f6-9c046390cda0
