### ISSUE TITLE
Ingest "Nassau Lit" (pudl0141)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1632]
Notes: Ask Cliff

Where does this go?

@cwulfman Again, not sure what the details are here. Can you give some background on the "Nassau Lit" collection and tell us if we're to ingest it into Figgy? Also any info you have on if it's being displayed anywhere?

**Comment by cwulfman** [comment]
See comments on issue #1626.

**Comment by roelmoon** [comment]
The images are in the "princetonperiodicals" share of the Isislon. This was a Mudd archives project. I believe the images were being sent out for OCR and structural markup, but not sure who the vendor was. Rachel Van Unen was the contact, probably should get in touch with Dan since she's left. I believe the ultimate goal was to get this collection into Veridian.

**Comment by cwulfman** [comment]
Concurring with Roel; see http://papersofprinceton.princeton.edu/princetonperiodicals

**Comment by escowles** [comment]
This collection has been ingested into Veridian: http://papersofprinceton.princeton.edu/princetonperiodicals/ — there are outstanding issues about how Veridian content interacts with Figgy, but we can handle that in another issue.
