### ISSUE TITLE
Should ARKs for objects in DPUL point there instead of PULFA/OL?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1643]
* If an item is public in DPUL, should the ARK point to the object there?
* If so, should we try to figure out which collection is the "main" collection, or point to the top-level object?

**Comment by escowles** [comment]
@sdellis The main thing I was thinking of is objects that are in several Figgy collections with differing status in DPUL, possibly:
1. a "treasures" collection that is public in DPUL
2. a narrower collection that may or may not be public in DPUL
3. an even narrower collection that serves to create a browse category or collection facet in DPUL, but will never have its own DPUL collection

How would Figgy know which of those to link to?  We could add a property to collections that said "link to items of this collection in DPUL instead of PULFA/OL", but if 1 and 2 above both had that selected, what should Figgy do?

Linking to the top-level (non-collection-specific) DPUL resource avoid needing to choose between multiple collections (and would perform better since we wouldn't need to load/inspect them).

**Comment by hackmastera** [comment]
Once you're on a top-level object does it say what collections it's part of?

**Comment by escowles** [comment]
It does: https://dpul.princeton.edu/catalog/m613n219p

Though the collections are not links, even if there are DPUL collections for them.  I'll make a DPUL ticket to fix that.

**Comment by hackmastera** [comment]
👍 I think with links to collections the top-level object would be all anyone would need

**Comment by sdellis** [comment]
My only concern with this solution is that the Collection is usually a critical part of the citation, even with an ARK. Citing this example as part of our _Ethiopic Manuscripts_ collection would be more accurate and helpful to a scholar than citing it as part of _Princeton's Treasures_, which is more oriented to the general public. In other words, we need to provide more guidance around what the "official" collection is.  We also need to provide exact titles since we have multiple archival Ethiopic Manuscripts collections, none of which are titled "Ethiopic Manuscripts". 

My recommendation would be to provide links for ALL of those fields. Furthermore, the Rights Statement should show the title, not the URI. In this instance, it should say "No known copyright," and provide a link to the full statement.

**The optimal experience, and one that most archives have (including ours), would be to provide a preferred citation** as mentioned in [Purdue's archival research guidelines](https://owl.purdue.edu/owl/research_and_citation/conducting_research/archival_research/digital_archives_materials.html). You can see the "preferred citation" for the analog item on [its Finding Aid page](https://findingaids.princeton.edu/collections/C0776/c00837). If ARKs are going to point to DPUL, we should have a similar preferred citation field for the digital object.

**Comment by escowles** [comment]
@sdellis If you would like to discuss the display on that page, go ahead and open a ticket in Pomegranate.  I'm sure there is more we can, and should, do there.

The only thing in scope here is what URL the ARK should be configured to redirect to.  If we want to have that URL be a collection-specific one, then we are back to the question: how does Figgy figure out which collection to use, out of potentially many collections a Figgy object can be a member of?

Some options:
1. Collections have a field that says "link to DPUL for objects in this collection".  We resolve the multiple collections issue by:
  a. Trying to avoid having objects in multiple "DPUL-linked" collections.
  b. We pick the first one that is "DPUL-linked".
  c. We implement a check that finds potential conflicts and warns and/or prevents creating the conflict.
  d. Instead of a boolean, we have a priority number, and the collection with the highest priority number is used.
2. Each object has a single-valued field that is the DPUL collection to link to.  If this is set, then we link to that collection, otherwise the current PULFA/OL URL is used.

**Comment by sdellis** [comment]
@escowles thanks, I will go ahead and open an issue in pom. To answer your question in scope:

**The URL the ARK should be configured to redirect to should have our own "preferred citation" information on it for the digital object.** PULFA/OL already have this information for the analog objects, so until we have preferred citations for digital objects, I think it's best to always point the ARK to those records (which will display the embedded digital content).

**Comment by tpendragon** [comment]
It's been so long I think the answer is "no."
