### ISSUE TITLE
Ensure that FileSet parent visibility is accessible when they are being deleted

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1664]
## Backtrace

    line 61 of [PROJECT_ROOT]/app/services/geoserver_message_generator.rb: parent
    line 96 of [PROJECT_ROOT]/app/services/geoserver_message_generator.rb: vector_resource_parent?
    line 54 of [PROJECT_ROOT]/app/services/geoserver_message_generator.rb: layer_type

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39113018)

**Comment by jrgriffiniii** [comment]
As described by @eliotjordan , currently a `FileSet` for a geospatial resource will be deleted, following which a message describing this event will be published for consumption by GeoBlacklight.  In order to pass the proper workspace ID (for GeoServer data layers), the visibility of the parent resource to the `FileSet` must still be available.

**Comment by tpendragon** [comment]
Closed as this is the staging version of #1669
