### ISSUE TITLE
[Figgy/staging] NoMethodError: undefined method `internal_resource' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1678]
## Backtrace

    line 4 of [PROJECT_ROOT]/app/change_sets/dynamic_change_set.rb: new
    line 73 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: attach_children
    line 42 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: attach_dir

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39165043)

**Comment by tpendragon** [comment]
I think this is because `new_resource` is creating an invalid resource.

**Comment by christinach** [comment]
This issue looks to be a case of a wrong ingest : "jobstr" => "{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"IngestFolderJob\",\"queue\":\"low\",\"args\":[{\"job_class\":\"IngestFolderJob\",\"job_id\":\"6c8b2700-5886-40d1-962b-f7999b0fc142\",\"provider_job_id\":null,\"queue_name\":\"low\",\"priority\":null,\"arguments\":[{\"directory\":\"/mnt/diglibdata/pudl/pudl0020/vol01/001\",\"member_of_collection_ids\":[\"e537f73d-70af-4b7f-8c5f-559a76ec39f2\"],\"source_metadata_identifier\":null,\"local_identifier\":\"pudl0020/vol01/001\",\"replaces\":\"pudl0020/vol01/001\",\"_aj_symbol_keys\":[\"directory\",\"member_of_collection_ids\",\"source_metadata_identifier\",\"local_identifier\",\"replaces\"]}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"bb490caa9215a5001d9cdcb4\",\"created_at\":1534790295.2920637,\"enqueued_at\":1534798660.1779904,\"error_message\":\"undefined method `internal_resource' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at\":1534795196.2444308,\"retry_count\":1,\"retried_at\":1534798603.9611936}"

The specific error is because:
https://github.com/pulibrary/figgy/blob/71051e6645773c32ff3ba6f5a6db486f9e5b7224/app/services/bulk_ingest_service.rb#L29

returns an invalid url. in this case : https://bibdata.princeton.edu/bibliographic/101/jsonld

one solution would be to add a rescue in the method:
def valid_remote_identifier?(value)
    RemoteRecord.retrieve(value).success?
    rescue 
      Rails.logger.error(" #{e} https://bibdata.princeton.edu/bibliographic/#{base_name}/jsonld is not a 
      valid url")
end

After discussing with @tpendragon, we decided to mark the honeybadger error as resolved and if it happens again then to take care of it.
