### ISSUE TITLE
Remove SimpleResources

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1766]
An alternative implementation would be that we provide forms for ScannedResources using a different ChangeSet that allows them to input metadata.

That way we can use all the same views for everything but the form. Maybe the route would be something like `/concern/scanned_resources/metadata/new` ?

**Comment by tpendragon** [comment]
https://github.com/pulibrary/figgy/compare/simple_resource_as_change_set is a quick and dirty spike to see what this would look like. This makes it so `/concern/scannned_resources/new/simple` makes a SimpleResource, which saves the fact that it's "simple" to the resource, and thus makes edit/update/workflow/etc load up a SimpleResourceChangeSet.

**Comment by tpendragon** [comment]
Some things to ponder:

1. Would this be confusing to look at as a new dev, or is it offset by the fact it's less code? 
2. Are we just abusing the fact that our forms are dynamic based on a method in the changeset this way? Is that okay? I guess we could still render forms based on what changeset is passed in, but it doesn't look Railsy. 
3. If we do this what's the use case for a second Valkyrie::Resource? A different set of metadata? I guess if controller logic needs to differ? Unlikely, since that's all in ChangeSetPersister. 
4. Does this bind change sets to their resource too much? This might be an even more flexible approach, but I dunno. 

This FEELS right to me, but experience tells me that feeling is often a trap.

**Comment by escowles** [comment]
I suspect it would be less clear to a new dev, to have the forms driven by the ChangeSet instead of the model.  But I do like the separation of behavior into ChangeSets.  Though this is starting to remind me of UCSD's data model (where the was just one model called `Object`, and all behavior was driven by mime types of content files).

**Comment by tpendragon** [comment]
Yeah, OD was the same way - want to make sure this isn't just comfortable territory.

**Comment by tpendragon** [comment]
I'll work on a PR for this and maybe we just try it out. It should be easy to migrate from - if it works I think it opens similar questions about MediaResource.

**Comment by hackmastera** [comment]
I don't think valkyrie is super railsy in general. I have the same question about when we would use another model. But we are already putting all the fields everywhere, really, it's already a bunch of schemas that look the same and use different models because they have different behaviors. Maybe it makes plenty of sense to essentially have a "resource" model and then other models would be for things like file sets, and nested resources of various kinds -- truly different models.
