### ISSUE TITLE
Investigate wowza integration

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1990]
Also, research wowza features, e.g. is there a player?

child of #1986

**Comment by tpendragon** [comment]
There is indeed a wowza player: https://www.wowza.com/docs/wowza-player-javascript-api-overview

**Comment by jrgriffiniii** [comment]
As no e-mail responses have been received, I'm going to attempt to contact OIT by creating a SN@P ticket for my questions regarding Princeton Wowza installations.

**Comment by jrgriffiniii** [comment]
The SN@P issue has been created: https://princeton.service-now.com/snap?sys_id=9fc39bdadb9563c4a341de82ca961954&view=sp&id=ticket&table=incident

**Comment by jrgriffiniii** [comment]
I have a meeting schedule with Dwight Bashore for this afternoon at 03:30PM in order to discuss this in greater detail.

**Comment by jrgriffiniii** [comment]
After discussing our needs with the Collaboration Infrastructure Analyst, it was clarified that Kaltura and Wowza are tightly coupled for the vast majority of cases on campus, and that we would be best using Kaltura only.

At this point in time, Kaltura a Princeton functions using Wowza as a cloud-based streaming service, or using local servers.  A client will request an HTML page with an embedded viewer from a web server.  Should this be a client which lies within the `*.princeton.edu` domain (e. g. a student on the Princeton network), then the Princeton Wowza servers are used to stream the media to the client using the embedded player.  Should these clients be from the outside world, then the Kaltura cloud service (which also uses its own Wowza servers) stream to these clients.  This architecture was implemented in response to the excessive costs originally incurred when both clients inside and outside of the Princeton network requested media streams exclusively from the Kaltura cloud.

An embedded HTML5 viewer will be provided with a URL generated from Kaltura.  Currently the viewer is actually provided by Kaltura using the following widget:

https://github.com/kaltura/EmbedCodeGenerator

This provides JavaScript (dynamically appended to the DOM Document) to generate an HTML5 viewer for the following MP4:

http://cdnsecakmi.kaltura.com/s/p/423851/sp/42385100/serveFlavor/entryId/1_znvt6hgh/v/1/flavorId/1_rhn6z6sv/forceproxy/true/name/a.mp4?aeauth=1540412706_8ecb502db763454a8777c49738b8a4b9

This MP4 is, ultimately, provided from an underlying Wowza server.  There would be little purpose in looking to work around Kaltura in order to access this more directly.
