### ISSUE TITLE
Determine display of audio reserve links from blackboard

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1991]
- where will this live? figgy? dpul? etc?
- does wowza have a player? If not, UV?

child of #1986

**Comment by jrgriffiniii** [comment]
Following a discussion on Slack, it was determined that it would be best to approach this by preferring the Kaltura player (due to the significant differences between the IIIF Presentation API and those responses provided by the Kaltura server): https://pulibrary.slack.com/archives/CA8282VKN/p1540304288000100

Regarding the location of where these might be served, it was also determined that access-restrictions for DPUL exhibits are possible, but might not be immediately necessary: https://pulibrary.slack.com/archives/CA8282VKN/p1540303572000100. Please see https://github.com/pulibrary/pomegranate/issues/434 for this feature request.

Also, this relates to https://github.com/pulibrary/figgy/issues/1993

**Comment by jrgriffiniii** [comment]
This is also blocked by https://github.com/pulibrary/figgy/issues/1990 (I am still waiting for a response regarding the state of Wowza installations at Princeton).  However, whether or not this is truly blocking may be a matter of prioritization, as the Kaltura viewer could be ported from the existing music reserves interface.

**Comment by jrgriffiniii** [comment]
Given that it was recommended by OIT that Kaltura exclusively be used, there are two solutions supported by the company which could be offered for an embedded viewer:
* https://github.com/kaltura/EmbedCodeGenerator
* https://github.com/kaltura/playkit-js

Depending upon what can be retrieved from the API (which is being determined in https://github.com/pulibrary/figgy/issues/1995), there may be additional players which could be supported:
* https://github.com/videojs/video.js
* https://github.com/mediaelement/mediaelement/blob/master/docs/api.md#attributes
* https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#playlist
* https://github.com/sampotts/plyr#html

**Comment by tpendragon** [comment]
Why are we using Kaltura if it doesn't do Auth and we're ingesting these items anyways?

**Comment by tpendragon** [comment]
So the current player links don't auth at all. It seems like it would be pretty easy to generate mp3s of the WAV files and just feed them through nginx like we do for our other audio material.

**Comment by jrgriffiniii** [comment]
I have not received any responses from Kaltura for my enqueries regarding cases where we would need to ensure that an HTML5 player provides some form of SSO-support or session-based authentication using a token.  What you've found is significant, and I'll review the documentation in search of some solution.

**Comment by jrgriffiniii** [comment]
#2015 will resolve this
