### ISSUE TITLE
Migrate audio reserves data

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2043]
Child of #1986

**Comment by hackmastera** [comment]
We should evaluate whether we can pull data directly from the db, or whether we need to use some intermediate format in order to massage the data.

The `tiny_tds` gem does work for accessing the database. first do `brew install FreeTDS`, add the gem to the Gemfile, and you can query the db as shown on https://www.microsoft.com/en-us/sql-server/developer-get-started/ruby/mac/step/2.html (credentials, etc, in keybase)

**Comment by hackmastera** [comment]
How about a list of tables in the db sorted by what we will / won't migrate:

Data to migrate:
```
Selections  # these become playlists
  idSelection (int)
  idRecording (int)
  idComposer (int)
  Title (nvarchar)
  AltTitle (nvarchar)
  SelNote (nvarchar)
  AudioFiles (bit)
  Time (smalldatetime)

jSelections  # use this to add a course field (string) to each selection
  idCourse (int)
  idSelection (int)
  ClassSort (varchar)
  Time (smalldatetime)

Recordings  # These become Recording / MusicReserves resources
  idRecording (int)
  RecTitle (nvarchar)
  CallNo (nvarchar)
  idType (int)  # map directly to the string in the types table
  RecNote (nvarchar)
  Pulled (bit)

AudioFiles  # we'll have to navigate through selections to put these on the right Recording / MusicReserves resource
  idFile (int)
  idSelection (int)
  FilePath (nvarchar)
  FileName (nvarchar)
  FileNote (nvarchar)
  Time (smalldatetime)
  entryid (nvarchar)

jTeachers  # use this to add an instructors (strings) to Playlists
  idCourse (int)
  idStaff (int)

trackSelections  # not sure what these are
  idSelection (int)
  wav (bit)
  rm (bit)
  ra (bit)
  ram (bit)
  linked (bit)
  scanned (bit)
  note (varchar)
```

Tables to migrate only in as much as we pull over their string values / flatten them out of existence:
```
Composers
  idComposer (int)
  Composer (nvarchar)

Types
  idType (int)
  Material Type (nvarchar)
#    (3,'Book'),
#    (2,'SCORE'),
#    (1,'Sound recording'),
#    (4,'Video');

Staff  # we'll add instructor names to playlists
  idStaff (int)
  Name (nvarchar)
  Office (nvarchar)
  Phone (nvarchar)
  Email (nvarchar)
```

Tables we won't migrate:
```
jAudioFiles  # join table for course / file?
  idCourse (int)
  idFile (int)
  SortOrder (smallint)
  Time (smalldatetime)

Courses
  idCourse (int)
  CourseNo (nvarchar)
  Title (nvarchar)
  idSemester (int)

Current Semester
  idSemester (smallint)

Results  # no data in this table
  idSemester (int)
  Semester (nvarchar)

dtproperties  # no data in this table
  id (int)
  objectid (int)
  property (varchar)
  value (varchar)
  uvalue (nvarchar)
  lvalue (image)
  version (int)

Semesters
  idSemester (int)
  Semester (nvarchar)

Logon
  idCourse (int)
  UserId (nvarchar)
  Password (nvarchar)
  Note (nvarchar)
  Inactive (bit)

FallMusicCourses2014
 idCourse (int)
 CourseNo (nvarchar)
 Title (nvarchar)
 idSemester (int)

SpringMusicCourses2014
  idCourse (int)
  CourseNo (nvarchar)
  Title (nvarchar)
  idSemester (int)

mus226new
  recnum (float)
  FilePath (nvarchar)
  FileName (nvarchar)
  FileNote (nvarchar)
  CourseNo (nvarchar)
  File ID (nvarchar)

mus234new
  recnum (tinyint)
  filepath (nvarchar)
  filename (nvarchar)
  FileNote (nvarchar)
  Class (nvarchar)
  Assigned (datetime)
  idFile (bigint)

```

**Comment by tpendragon** [comment]
Are we going to migrate courses, teachers, composer, etc? I thought we were going to just drop that data and leave it to Ares, and just bring over -maybe- the call number.

**Comment by hackmastera** [comment]
We've decided to map call numbers to bib ids (on Recording resources).

Then we won't bring instructors, composers, or other descriptive metadata because we will import metadata from voyager. Metadata from voyager doesn't currently import a call number. We should save it in its own searchable field for now.

If the call number does not map to a bib id
If there is a recording that maps to the same files (i.e., has audiofiles that have the same filepaths), and that recording has a call number that does map to a bib id, the first recording is a playlist and the second is a recording.

**Comment by hackmastera** [comment]
It looks like the recordings that have been used as playlist workarounds have call numbers beginning with `x-` e.g. `x-mus258_AfricanMinimilism`

**Comment by hackmastera** [comment]
pilot data was migrated
