### ISSUE TITLE
Playlists have tracks

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2080]
* Tracks can be added or removed
* Tracks are ordered
* Removing a track from a playlist does not delete the FileSet
* Track titles should default to the FileSet label, but should be able to be customized to the playlist context without updating the FileSet
* Tracks should not show up in search results

Child of #2066

**Comment by hackmastera** [comment]
We've agreed to implement tracks as members on Playlists, where tracks use a new resource class called ProxyResource. ProxyResource have their own id, a label, and the id of the resource they proxy.

**Comment by jrgriffiniii** [comment]
The current progress of this issue is as follows:
- [ ] Tracks can be added or removed
- [x] Tracks are ordered (https://github.com/pulibrary/figgy/pull/2120)
- [x] Removing a track from a playlist does not delete the FileSet (https://github.com/pulibrary/figgy/pull/2121)
- [x] Track titles should default to the FileSet label, but should be able to be customized to the playlist context without updating the FileSet (https://github.com/pulibrary/figgy/pull/2121)
- [x] Tracks should not show up in search results (https://github.com/pulibrary/figgy/pull/2120)
