### ISSUE TITLE
Copy recent numismatic images to Isilon

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2089]
A quick survey shows there are at least some images of coins not in the puld0049 directory. It would be useful to have a list of the missing images so we can track them down.

Child of #2242

**Comment by escowles** [comment]
Alan said that Roel has been copying them from their hard drive, and returning the drive empty.

**Comment by escowles** [comment]
I asked Roel if there were other images beyond what we see in pudl0049 (which are a few years old), and he said he hadn't done anything since then, and any other images are on their hard drive in RBSC.  So when we get ready to migrate data, we should ask Roel to copy all of their files to the Isilon again, so we have the most recent images.

**Comment by eliotjordan** [comment]
Will need to be done right before migration.

**Comment by jrgriffiniii** [comment]
The image files have been copied, but there still must be resources created in response to these new assets within Figgy (I believe that this is a CLI Rake task or something similar).

**Comment by eliotjordan** [comment]
Images ingested and linked to Coin records.
