### ISSUE TITLE
Save and Ingest should look in the music library's ingest directory when ingesting a Recording

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2204]
Add a way to have configured "Save and Ingest" location change based on change set.

requires #2295

**Comment by escowles** [comment]
I added some relevant functionality to IngestFolderLocator a couple weeks ago, but it's been lost since then: https://github.com/pulibrary/figgy/pull/2122/files#diff-13b3753be444294bf522d176cbd7f9dc

Basically, I think we have the same use case for numismatics, so developing a general solution to types being ingested from different directories seems like the way to make Save & Ingest work for everybody.
