### ISSUE TITLE
Attempt to call id on nil when forming download link in manifest builder

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2322]
[Figgy/staging] NoMethodError: undefined method `id' for nil:NilClass

## Backtrace

    line 413 of [PROJECT_ROOT]/app/services/manifest_builder.rb: download_url
    line 420 of [PROJECT_ROOT]/app/services/manifest_builder.rb: display_content
    line 103 of [PROJECT_ROOT]/app/services/manifest_builder.rb: block in audio_manifest?

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/43101730)

**Comment by hackmastera** [comment]
I couldn't replicate this. Maybe the viewer was trying to load the manifest before the derivative was finished generating? I am not sure which `id` is called on `nil` since the method calls `id` on both `resource` and `derivative`. I suspect to a user this looks like an empty viewer or a viewer with an error and not a full 500 error page.

**Comment by tpendragon** [comment]
Marked as resolved and closing. We can reopen if it happens again.
