### ISSUE TITLE
Update preservation bags when files or metadata are updated

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2554]
Child of #1876

To efficiently update preservation bags, don't re-upload unchanged files.

**Comment by tpendragon** [comment]
Do we still want to do this? Creating a bag is pretty expensive, both monetarily and in compute resources, and there are a lot of saves that happen when it comes to things like "add a page and put it in the right spot in the book." Maybe we just need a notification if the uploaded date on the bag is less than the modified date of the resource, with a button for "preserve me again please"?

Alternatively we could have some sort of cron job to automatically do a re-persist if a thing hasn't been changed in some span of time, but has been changed since the bag was preserved (like...a week? A couple weeks?)
