### ISSUE TITLE
[Figgy/production] NameError: uninitialized constant Types::RasterResourceType

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2614]
## Backtrace

    line 25 of [PROJECT_ROOT]/app/graphql/types/resource.rb: resolve_type
    line 20 of [PROJECT_ROOT]/app/controllers/graphql_controller.rb: block in execute
    line 114 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: block (2 levels) in buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/45932987)

```
https://catalog.princeton.edu/catalog/10134082
```

**Comment by eliotjordan** [comment]
See: https://github.com/pulibrary/figgy/issues/2411

This is still raising errors.

**Comment by eliotjordan** [comment]
This is still happening because Orangelight is requesting an object's members to filter out child ScannedMaps in a MapSet.

https://github.com/pulibrary/orangelight/blob/master/app/javascript/orangelight/figgy_manifest_manager.js#L118

What's causing the error, is that when a ScannedMap resource has a child RasterResource, the query is requesting it's members, but there's no RasterResource graphql type in Figgy.

My suggestion is to invert the logic and have Figgy filter out the child scanned maps instead of doing that in Orangelight. This way Orangelight does not have to query for members of each resource. 

https://github.com/pulibrary/figgy/blob/master/app/graphql/types/query_type.rb#L31

Maybe add a `.select { |r| r. parents.nil? }`

This the added advantage of reducing the information of GraphQL payload. This Sanborn in the catalog returns 68 resources. We could reduce this two one by filtering in Figgy.

https://catalog.princeton.edu/catalog/5355769

![screenshot 2019-02-21 16 01 30](https://user-images.githubusercontent.com/784196/53205553-43f60600-35f4-11e9-9a7c-31a62fb513b8.png)

**Comment by eliotjordan** [comment]
I think adding Raster and Vector types is a good thing to do in addition, BTW.
