### ISSUE TITLE
New content type: letters

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2649]
This is probably a SimpleResource with:
* Images of the letter page(s) and envelope
* Draft/published workflow
* Collection membership
* Source metadata identifier (linking groups of letters to a bib record or finding aid component)

And forms for entering the following metadata:
* Sender name and place
* Recipient name and place
* Date

**Comment by escowles** [comment]
Deadline: 10/1/2019, when this collection will be opened, processed, and digitized: https://findingaids.princeton.edu/collections/C0686

**Comment by tpendragon** [comment]
The type is here as of #2733, but we'll need to figure out what exactly the ingest workflow is going to be like.

**Comment by tpendragon** [comment]
@escowles We're about to ice box this, but just realized our deadline is passed. Should we be worried about these? Leaving in the backlog for now.

**Comment by tpendragon** [comment]
The material for this collection is meant to be very private and only accessible from reading room laptops. The material provided should be the high resolution TIFFs alongside the finding aid. The material hasn't been looked at yet, when it is they'll have an idea of what the overall process will be.

The current recommendation is rather than using the Figgy form they'll add components for each item to the finding aid and Roel will ingest using bulk ingest at the appropriate time.

**Comment by escowles** [comment]
Closing this ticket, since the Hale/Eliot collection was ingested as Scanned Resources and accessed as PDFs linked to a static HTML version of the finding aid (like the Toni Morrison collection).
