### ISSUE TITLE
intermittent order manager save problems

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2657]
Report from Tom: The past two days, if I go into Order Manager for an item and order-paginate or otherwise rename images, I find that the changes do not hold for several (seemingly random) images.  It usually takes a few iterations for me going back in and manually renaming the images for the changes to hold.  I am clicking "Apply Changes" after each individual name change and waiting until the change is confirmed before moving on

**Comment by tpendragon** [comment]
We're having trouble replicating this. We need to schedule a call with Tom to see this in action.

**Comment by tpendragon** [comment]
The problem here is background jobs overriding FileSets. Tom is setting an OCR language, which spawns a bunch of RunOCR jobs. When he edits the files in the OrderManager, the OCR jobs are running with out-of-date data, and when they save they override the changes he's made. So it goes RunOCRJob Starts -> Order manager Saves -> Run OCR Job Saves -> Order manage changes are gone.

To stop data corruption (maybe with a not-great user experience, but better than nothing) we'll have to implement optimistic locking (see #1874).

A short term band-aid would be to make RunOCRJob have as little time as possible between pulling the object and saving it, and making it so updates don't spawn CheckFixityJobs (as per #2431).

**Comment by escowles** [comment]
Optimistic locking should work well for this: when the OCR job tries to save, it'll throw an error if the fileset has been updated. Then the OCR job can reload the fileset, add the OCR text, and retry saving.

**Comment by tpendragon** [comment]
The "band-aid" solution is turning out a little more involved than we expected. It's turning out that DerivativeServices should be pulling the resource at the beginning of its processing if it's going to be updating it, so we're changing the method signature to accept an ID instead of a ChangeSet.
