### ISSUE TITLE
CheckFixityJob should not throw an error if a file is not found

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2674]
If a file isn't found, it means it was probably deleted before the Fixity job could be run.

## Backtrace

    line 27 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in trace
    line 43 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38673293)

**Comment by tampakis** [comment]
Happens also for CreateDerivativesJob

**Comment by hackmastera** [comment]
I'm unlinking this from the HB issue because we'll want to resolve that when the specific file is dealt with (#3567) so that we can get a new alert if there's another problem.

The assumption in the write-up of this ticket is that the fixity job is failing on resource creation. However, we're currently observing the job failing on a broken object that's coming up for fixity check via the recursive fixity check job. So I'm not sure just swallowing the error would be enough. The recursive fixity job would just pull the same file set again the next go-round, and wouldn't ever be able to get past the broken file set until it was fixed or deleted.

**Comment by tpendragon** [comment]
Duplicate of #4521
