### ISSUE TITLE
read-only mode breaks searching

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2875]
[Figgy/production] ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for relation searches: INSERT INTO "searches" ("query_params", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/48219303)

**Comment by jrgriffiniii** [comment]
I'm uncertain as to what triggered this, but if anything, it related to PostgreSQL administration and the size of the `searches` table (normally rows are unlimited in size, please see https://wiki.postgresql.org/wiki/FAQ#What_is_the_maximum_size_for_a_row.2C_a_table.2C_and_a_database.3F)

**Comment by tpendragon** [comment]
Seems like this was probably an unintended side effect of read-only mode.

**Comment by hackmastera** [comment]
When you do a search in blacklight it adds the search to your session's search history by creating an `ActiveRecord` `Search` object.

This does seem to mean that read-only mode will make searching return errors. I have just confirmed on staging. Probably it didn't turn up during initial testing on staging because I did not try a unique search; I only ran a search which would have been retrieved from my history rather than requiring that `create`.

**Comment by hackmastera** [comment]
Figgy doesn't provide links to search history. Is it reasonable to try to override this code in some fashion either generally or with a check for read-only mode?

**Comment by tpendragon** [comment]
Doesn't it use the search history for the "back to search" button?

**Comment by hackmastera** [comment]
I would believe that. Maybe we can brainstorm solutions to this on the next call.

**Comment by hackmastera** [comment]
Of note: saved searches are deprecated in blacklight 7 https://github.com/projectblacklight/blacklight/wiki/Saved-Searches
