### ISSUE TITLE
Consider OCFL for preservation storage

### ISSUE THREAD

**Issue by rosy1280** [pulibrary/figgy#2884]
https://ocfl.io/

**Comment by tpendragon** [comment]
Thank you for creating the issue! We did look at this, but weren't super public about it, and I don't think I shared my findings very well. I'm writing up a long-form response to this now, because I think there's a lot to say, but here's the basic structure so far:

![Screen Shot 2019-04-16 at 12 32 43 PM](https://user-images.githubusercontent.com/2806645/56239479-f58a4400-6045-11e9-844d-979ec2cbaf06.png)

![Screen Shot 2019-04-16 at 12 49 15 PM](https://user-images.githubusercontent.com/2806645/56239526-194d8a00-6046-11e9-83d5-0b10a852b1f6.png)

**Comment by rosy1280** [comment]
An immediate question comes up re: 

> Store objects and its children in a hierarchy we can easily navigate

What is an object? Is a book an object, is a page an object, or is a file an object?

**Comment by tpendragon** [comment]
> What is an object? Is a book an object, is a page an object, or is a file an object?

Thanks, I'll try to clarify that.

An object marked for preservation is an "object" (there's a field in Figgy). In reality, it's a "book" - the top-level of a hierarchy. We chose this boundary so we could pass around what is most commonly handed around. So a multi-volume work will have itself, then under it a couple volumes, and under each volume a bunch of pages, where pages have both metadata and a binary attached.

**Comment by mjgiarlo** [comment]
For folks who land here, you will want to read @tpendragon's handy and thorough blog post going into more detail: https://pulibrary.github.io/2019-04-16-preservation
