### ISSUE TITLE
LA bag ingest - Emir Rodriguez Monegal Papers resource with no component id

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#3018]
One item in the Emir Rodriguez Monegal Papers came through with no title, presumably because it couldn't find a component id.

https://figgy-staging.princeton.edu/catalog/d3d35fa2-8ecb-4a13-a24e-4aedabb3d607

@kellybolding

**Comment by kellybolding** [comment]
@hackmastera 
See notes here: https://docs.google.com/spreadsheets/d/1L74AvaernYHErzNgmtvvczRtVDSIrjNknaUc-kWXbRQ/edit#gid=594821225

I didn't change the EAD here. All of these were missed because of the difference in the file naming convention, as mentioned in the ticket for C1502. We'll need to ingest manually and/or modify the process to accept file names with the _p1, _p2, _p3, I think. Let me know if there's an alternative solution!
