### ISSUE TITLE
Rake task to set all current Recordings to be unable to be downloaded.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3074]

**Comment by hackmastera** [comment]
If they're not set this way currently, how are they being suppressed in the viewer?

**Comment by escowles** [comment]
Because we were suppressing download for all Recordings, I think we just suppressed that in the manifest, instead of using the newer per-resource mechanism to suppress downloads.  So if we start supporting downloads for some Recordings, we need to make sure we don't accidentally enable downloads for Audio Reserves Recordings.

**Comment by christinach** [comment]
we disabled the download button in the ui https://github.com/pulibrary/figgy/pull/2161/files

**Comment by hackmastera** [comment]
Ah, thank you for that @christinach I could not find the code that was doing this.

So I think we'll want a ticket to revert that so the new mechanism will come through, yes?

**Comment by escowles** [comment]
@hackmastera Do we need anything beyond #3071 ?

**Comment by hackmastera** [comment]
@escowles ah, nope! I will add the code pointer there. thanks.
