### ISSUE TITLE
JSON/LD for records need to be accessible for all complete items that are not private

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3204]
So that dpul can index all records even though we lock down manifests.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/compare/issues-3204-jrgriffiniii-json-ld-accessible addresses this with support for a `harvester` auth. token.  It's failing due to some conflict with the authorization for `SolrDocument` access abilities beyond the override here: https://github.com/pulibrary/figgy/blob/master/app/models/ability.rb#L288

**Comment by hackmastera** [comment]
@jrgriffiniii I think the json/ld is meant to be broadly open; I'm not sure we want a token. https://github.com/pulibrary/figgy/issues/3205 is about a token and it should be for manifests. We didn't differentiate these 2 tickets well; refer to https://docs.google.com/document/d/1AKB1CRRc5g1BV1qstKvAA90xg042fizfyYZHGsMkVes/edit

**Comment by jrgriffiniii** [comment]
This was resolved by https://github.com/pulibrary/figgy/pull/3215
