### ISSUE TITLE
Preserve everything except Music Reserves

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3283]
This should be the default case, and we need to go back and preserve everything that hasn't been yet.

There could be a couple of different ways to do this, the important parts are:
1. Don't preserve Audio Reserves objects (new or future)
2. Other objects should be preserved by default
3. All current non-Audio Reserves objects should be preserved if they haven't been already

**Comment by eliotjordan** [comment]
How can one tell if a resource is a music reserve? Are all recordings music reserves?

**Comment by eliotjordan** [comment]
How about Ephemera? Preserve at the folder level? Box? Project?

**Comment by escowles** [comment]
For ephemera, I think folders are the right level to preserve.

Music Reserves is harder — we can probably identify them by having a call number starting with CD, but I don't know if that gets everything or not.

**Comment by hackmastera** [comment]
I don't think we have a reliable way to tell if something is a music reserve. We should talk about this more.

Currently the things I can think of are:
- Music reserves are likely to be linked to playlists
- Music reserves are likely to have a 'part of' field with a course number
- Music reserves are likely to have a bib number source metadata identifier

whereas:
- Archival recordings are currently modeled to be nested within another recording resource (a "descriptive proxy")
- Archival recordings will have a finding aid id as their source metadata identifier

So there are some things to grab onto here for initial settings, but I don't know that any of this is fair to rely on indefinitely. We'll ingest more things and change stuff around. I think we should talk about this more.

**Comment by escowles** [comment]
Maybe it should be "only preserve recordings that are part of an archival media collection"?

**Comment by hackmastera** [comment]
I guess we still have those! in the form of a change set.

**Comment by tpendragon** [comment]
:+1: to @escowles. That's the only reliable way.

**Comment by tpendragon** [comment]
Why would we not preserve boxes? One thing we need to be careful of too is that Collections have inverted membership but all its wayfinders act as if it doesn't, so if you preserve a "Collection" it'll preserve everything in it.

**Comment by escowles** [comment]
I don't think we should preserve ephemera boxes for two reasons:
1. Not all ephemera projects use them, and those that do have items that aren't in boxes, so it seems simpler to just preserve all folders instead of trying to figure out which folders aren't in boxes.
2. Boxes aren't a logical or intellectual grouping — they are just physical holders of not-necessarily-related folders.  So I expect that users would want to access a particular folder or set of folders, not everything in box 35.

**Comment by hackmastera** [comment]
Do they need to know the box to find an item, though? Or do they have that data in some other system? I.e. if figgy explodes and we have to restore from preservation copies, will we be sad we lost the boxes?

**Comment by escowles** [comment]
They need to know the box number and/or barcode to retrieve the physical item.  So preserving the box membership in the folder metadata would address that.  Does that happen now?

**Comment by tpendragon** [comment]
It's pretty cheap to preserve metadata-only boxes, and if Figgy explodes we'll need it to recreate the Figgy that existed before that right?

**Comment by escowles** [comment]
@tpendragon That is true — we should preserve the boxes so we can reconstruct the box membership.  I was conflating storing the boxes with storing folders nested in them, which is a different thing.

**Comment by eliotjordan** [comment]
This ticket proposes to preserve "everything", but that is a little misleading. A few thoughts...

- We should not preserve resource types that are only nested within other resources. Correct?
- The existing preservation logic only preserves resources that are "complete"., however there are a number of resource types without a state property. We will need to change the logic for these. I assume it's preserve on save when there is no state.
- There are handful of resources that I don't know if we should preserve or not (see below). 

Resource | Preserve | Has State Property
-- | -- | --
Collection | Y | Y
DateRange | N | N
EphemeraBox | Y | Y
EphemeraField | Y | N
EphemeraFolder | Y | Y
EphemeraProject | Y | N
EphemeraTerm | Y | N
EphemeraVocabularies | Y | N
Event |   | N
FileSet |   | N
MediaResource | Y | Y
NameWithPlace | N | N
NestedResource | N | N
NumismaticAccession | Y | N
NumismaticArtist | N | N
NumismaticAttribute | N | N
NumismaticCitation | N | N
NumismaticCoin | Y | Y
NumismaticFind | N | N
NumismaticFirm | Y | N
NumismaticIssue | Y | Y
NumismaticLoan | N | N
NumismaticMonogram | Y | N
NumismaticNote | N | N
NumismaticPerson | Y | N
NumismaticPlace | Y | N
NumismaticProvenance | N | N
NumismaticReference | Y | N
NumismaticSubject | N | N
PreservationObject |   | N
ProxyFileSet |   | N
RasterResource | Y | Y
ScannedMap | Y | Y
ScannedResource | Y | Y
Template | Y | N
Tombstone |   | N
VectorResource | Y | Y
WorkflowNote | N | N

**Comment by escowles** [comment]
@eliotjordan I think it might make sense to break down by a couple of different categories of resources:
1. "Works" and collections, e.g., ArchivalMediaCollection, Collection, EphemeraBox, EphemeraFolder, MediaResource, NumismaticCoin, NumismaticIssue, Recording, ScannedMap, ScannedResource, and VectorResource. The most convenient way to identify these is the resources with a state property, where we can preserve them when they are complete.
2. Nested resources — I assume these are never preserved because they are preserved in their parent resources.
3. Helper resources, e.g., most of the numismatic, ephemera, and controlled vocab fields, which should be preserved on every save.
4. The preservation machinery itself, like Event, PreservationObject, Tombstone. I don't know if these need to be preserved (maybe they need to be preserved so we can access historical versions if we do a complete restore?) — but there may be complications in preserving them and preventing recursive preservation processes.
5. FileSet is probably a special case — needs to be preserved, but only as part of a parent "work".

**Comment by tpendragon** [comment]
Regarding 2., nested resources are preserved individually - it's just that their test for "should I be preserved" is "does my parent say it's preserved"

**Comment by eliotjordan** [comment]
Do we need a `preservation_policy` property?

https://github.com/pulibrary/figgy/blob/master/app/change_sets/change_set.rb#L58

With cloud preservation as the default for all resources, this seems redundant to me. Also, it makes the implementation much simpler.

**Comment by escowles** [comment]
If it's easier to implement a rule-based selection method, then I'm fine removing the `preservation_policy` property.  We've talked about the possibility of there being multiple options, but I think in general we've talked about things that could be part of a rule-based approach, and we could revisit the need for a property if that becomes unworkable.
