### ISSUE TITLE
Order manager should have functionality to rotate images, and have that rotation show in the viewer.

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3503]
@kelea99 asked if we could add image rotation to the order manager. This would let us rotate images without having to edit and replace them. The main place we expect this could be an issue is with external ephemera contributors, but in theory it could happen with any image-based material.

**Comment by tpendragon** [comment]
We've talked about this before (maybe in Plum?), but I can't find the ticket. If I remember, we have two options: Either -actually- rotate the JP2 via a derivative regeneration process, or store a flag in the `FileMetadata` which will get read into the Presentation Manifest to say "rotate this image for the canvas by X", although I seem to remember from last time looking at this that there wasn't a great standard way to say the starting position - something about applying a CSS tag?

**Comment by tpendragon** [comment]
@kelea99 Was someone specifically concerned about this, or was somebody getting a bunch of images that needed rotating? When we've thought about this in the past it turned out it was really rarely a problem. Do you think we should close this until it happens?

**Comment by kelea99** [comment]
hi, @tpendragon ! This has come up a couple of times. Most recently it involved an external scholar who provided us with photography that  she took in the field for her research. Post-figgy ingest, she noted that many of her images needed to be rotated. It would be helpful if this could be done by the scholar in figgy, so it would not mean that someone on PUL's end who can read the language (me, in this example) would be responsible for rotating and then a re-ingesting the images in figgy. Does this make sense?

**Comment by tpendragon** [comment]
@kelea99 How was it handled this time? The studio just flipped them in photoshop or something?

**Comment by kelea99** [comment]
@tpendragon, I rotated them in photoshop and cropped (if needed) there as well. they were saved and ingested again.

**Comment by kelea99** [comment]
@tpendragon,  another use case for this (if helpful) from Vicki  in SC via email. "Alexis recently asked me to review and complete pending manuscripts in Figgy, and I have a question I’m hoping you can answer. Occasionally, some of the images need to be rotated to an upright position in order to be readable by the user. While I’m able to rotate the images in Figgy, I don’t see anyway to save the rotations in the record. Is there a way for me to do this, or do we just leave it up to the user to rotate the image when viewing the item record?"

**Comment by kelea99** [comment]
Another Use case for this: 
Collection: Grounds and Buildings
Submitted by Lynn Durgin:
Issue:  _Also, a handful of images have the incorrect orientation (upside down or backwards)—do you have thoughts on how to address this?_

I suggested she make note of it on the spreadsheet she is working on and I/Roel/techs would re-orient and re-ingest the images for the time being.

**Comment by kelea99** [comment]
Another use case: legacy items in finding aids that have random multiple rotations.  Example provided by Alexis Antricoli, and explained by Christa Cleeton: "So the issue with items like the example you noted is how they were ingested from isilon years ago. These are some of our legacy items that we had on the finding aids via webspace as well. I have been told that the only way to remedy is to re-ingest. The issue with a re-ingest is I don't always have the images saved. It has not been a priorty to fix these as you can still access them just not as cleanly as we would like. Anything that is getting ingested now does not have this issue."

Update from Alexis regarding these legacy items: We might have others like this and we are going to do a more global review and then I'll reach out.....nd none of this is a super rush, but we're hoping to get it completed by teh end of the year

**Comment by kelea99** [comment]
Another use case: microfilm reels with rando orientations, which has happened recently. @roelmoon , can you give the title of the most recent title that colleen was working on?

**Comment by sdellis** [comment]
I've seen rotation issues a lot, especially in Finding Aids manuscripts/docs. Isn't this what the IIIF Image API rotation parameter is for?

**Comment by escowles** [comment]
@sdellis Yes, it does seem like we could just point to the image api with the rotation parameter to generate the image with the orientation we want.

@tpendragon Is there any reason we can't do this? Storing a rotation value in the FileMetadata (or at the FileSet level) and then use that instead of hard-coding `0` when we generate the Image API URIs at https://github.com/pulibrary/figgy/blob/main/app/services/manifest_builder.rb#L757

**Comment by tpendragon** [comment]
Yes. The viewers use the info.json resource url, not that image.

**Comment by tpendragon** [comment]
One possible implementation is figuring out how UV handles a presentation manifest that somehow gives an initial rotation. The docs I've seen were conflicting so I don't know if it supports it.

**Comment by sdellis** [comment]
@escowles and @tpendragon I think this is something worth asking about on IIIF Slack. This is a use case that not only should be possible, but that the APIs were intentionally supposed to enable. I'm happy to follow up on this if you'd like. 

I agree that the docs are conflicting since [the spec says](https://iiif.io/api/presentation/3.0/#57-content-resources) "Content resources must have an id property, with the value being the URI at which the resource can be obtained.", but the [OpenSeadragon docs/examples](https://openseadragon.github.io/examples/tilesource-iiif/) only use the info.json resource url and never refer to the id. Which one is the correct resource for viewers to use?
