### ISSUE TITLE
Find missing PUO files

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#3532]
In a test ingest many files are not found on the mounted drive location.

**Comment by hackmastera** [comment]
Output of initial run is in deploy home on figgy-staging. file is called `puo_files.txt`

I'm adding the record id to the "Importing [titles]" log message in a forthcoming PR.

**Comment by hackmastera** [comment]
WIP:

Recordings that don't have any files in the old db:
```
idRecording,RecTitle,CallNo
3576,"Die Walkure - PUO (March 11, 2006)",cd-2006-03-11
1631,10/12/2002  Princeton University Orchestra Concert,x-musORCH 101202
1645,12/7/02 Princeton University Orchestra,x-musORCH 120702
1886,Symphony no.3,x-musORCH Mahler 3 042608
1423,Scheherazade concert 03/09/02,dat-2002-03-09
1424,"Symphonies of winds, etc. concert 03/09/02",dat-2002-03-09
1461,4/27/02 Princeton University Orchestra. Concert,x-mus ORCH 042702
5247,"Princeton University Orchestra, April 25 2009",cd-2009-04-25
6089,NULL,cd-2011-04-15
6090,PUO Spring 2011 Stuart B. Midlin Memorial Concerts,cd-2011-04-15

```

Recordings whose files weren't in the expected location:
```
idRecording,RecTitle,CallNo
3786,PUO - 04-23-2016,cd-2016-04-23
8432,"PUO Concert, December 6, 2018",cd-2018-12-06
8433,"PUO Concert - December 7, 2018",cd-2018-12-07
7508,PUO - 03-05-2016,cd-2016-03-05_PUO
7472,Princeton Unversity Orchestra,cd-2015-12-10

```

**Comment by tpendragon** [comment]
I'm asking Dan where the missing files for those recordings are. They have a weird naming convention (or the ones from 2002 do), so it's possible they've been renamed. Hopefully in some expected way.

**Comment by tpendragon** [comment]
Most of the files that are missing are just in newly named folders because Dan manually ingested them into Figgy. We can just not worry about those. There are a few early ones (mostly ones from 2002) that are legitimately missing. I've sent the list of all the missing files to Dan to work out.

**Comment by tpendragon** [comment]
I migrated everything to Prod, updated the ones already migrated to have the recording IDs/structure appropriately, and ran a report. 14 did not migrate, either because the files are in a different structure now or they're just not found. Here are the 14 I sent to Dan:

| idRecording | RecTitle                                                                          | CallNo                    | idType | RecNote | Pulled | 
|-------------|-----------------------------------------------------------------------------------|---------------------------|--------|---------|--------| 
| 1423        | Scheherazade concert 03/09/02                                                     | dat-2002-03-09            | 1      | NULL    | false  | 
| 1424        | "Symphonies of winds, etc. concert 03/09/02"                                      | dat-2002-03-09            | 1      | NULL    | false  | 
| 1461        | 4/27/02 Princeton University Orchestra. Concert                                   | x-mus ORCH 042702         | 1      | NULL    | false  | 
| 1631        | 10/12/2002  Princeton University Orchestra Concert                                | x-musORCH 101202          | 1      | NULL    | false  | 
| 1645        | 12/7/02 Princeton University Orchestra                                            | x-musORCH 120702          | 1      | NULL    | false  | 
| 1886        | Symphony no.3                                                                     | x-musORCH Mahler 3 042608 | 1      | NULL    | false  | 
| 3576        | "Die Walkure - PUO (March 11, 2006)"                                              | cd-2006-03-11             | 1      | NULL    | false  | 
| 5247        | "Princeton University Orchestra, April 25 2009"                                   | cd-2009-04-25             | 1      | NULL    | false  | 
| 6089        | NULL                                                                              | cd-2011-04-15             | 1      | NULL    | false  | 
| 6090        | PUO Spring 2011 Stuart B. Midlin Memorial Concerts                                | cd-2011-04-15             | 1      | NULL    | false  | 
| 7508        | PUO - 03-05-2016                                                                  | cd-2016-03-05_PUO         | 1      | NULL    | false  | 
| 8332        | "Princeton University Orchestra, April 26, 1997 in Richardson"                    | dat-1997-04-26            | 1      | NULL    | false  | 
| 8341        | "PUO, Glee Club, Princeton Pro Musica, PHS Women's Choir Concert, April 27, 2018" | cd-2018-04-27             | 1      | NULL    | false  | 
| 8342        | "PUO, Glee Club, Princeton Pro Musica, PHS Women's Choir Concert, April 28, 2018" | cd-2018-04-28             | 1      | NULL    | false  |
