### ISSUE TITLE
Numismatics reference ajax dropdown doesn't work with multiple nested resources

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3666]
<img width="775" alt="Screen Shot 2020-02-12 at 11 35 04 AM" src="https://user-images.githubusercontent.com/4650153/74356227-fede5d00-4d8b-11ea-8398-e55552544d14.png">

When clicking "add another citation" on the issue form, the "Numismatics reference" dropdown doesn't appear.

Also, it was requested to move the reference autocomplete field above the part and number fields

**Comment by eliotjordan** [comment]
Ajax drop drowns don't work on any multiple nested resources.

E.g. provenance, loan

**Comment by jrgriffiniii** [comment]
I was trying to resolve this by adjusting `app/javascript/helpers/setup_ajax_select.js`, but I now suspect that the Vue components should be bound when listening for https://github.com/nathanvda/cocoon/blob/v1.2.12/app/assets/javascripts/cocoon.js#L96

Otherwise, the partial provided with `app/views/records/edit_fields/_numismatic_citation_fields.html.erb` in `https://github.com/pulibrary/figgy/blob/master/app/views/records/edit_fields/_numismatic_citation.html.erb#L8` does not actually trigger the mounting of the `AjaxSelect` component.
