### ISSUE TITLE
"This website is under heavy load (queue full)" error popup

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3930]
this has happened to two of us just now, and Colleen has noted freezing with the claim button and save issues. 
<img width="1440" alt="Screen Shot 2020-05-20 at 12 32 56 PM" src="https://user-images.githubusercontent.com/45043014/82472442-2c772880-9a96-11ea-96b2-8b1720de517f.png">

**Comment by tpendragon** [comment]
It looks like some graphql queries (probably from OL?) were stuck for some reason and never finishing. Maybe because of the DB migration we're running? Anyways, it clogged up the request queue. Maybe we should find a way to make timeouts happen, but I'm not sure what a reasonable number would be. I'm gonna close this and if it happens again we can keep an eye on it.

Debugging Steps:

1. SSH into server.
2. `sudo passenger-status show=requests`
3. Look down requests and see what the path is for the active sessions.

Fixing Steps:

1. `sudo service nginx restart`

**Comment by hackmastera** [comment]
I've heard this error mentioned before; I think this does happen on the regular.
