### ISSUE TITLE
the William Henry Jackson Collection and the Sheldon Jackson Collection mapped the Collection Creator field rather than the Creator field for both "Creator" and "Publisher" fields in Figgy (and DPUL).

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3976]
Both creator and publisher are are pulling from the same field (Collection Creator) for these 2 collections (WC055 and WC054).

- Example: https://figgy.princeton.edu/catalog/0f6b93b2-e89e-4074-b069-9a55583a6519

Strangely, creator and collection creator are being mapped properly for WC064.

- Example: https://figgy.princeton.edu/catalog/278946cd-4198-4bbd-8dc0-652fc706f15a. 

Request:
I would like collection creator in finding aids to be mapped to publisher in figgy and DPUL.

I would like creator in finding aids to be mapped to creator in figgy and DPUL.

**Comment by tpendragon** [comment]
@kelea99 I added this to Figgy and the Digital Project's backlog. Maybe it should go somewhere in the PUDL migration board and not the digital projects board? Can you just put this in the appropriate place for me?

**Comment by kelea99** [comment]
@tpendragon  will do!  @cwulfman , see above. thoughts? moved ticket to PUDL migration backlog.

**Comment by cwulfman** [comment]
These were ingested before the collection publisher/creator mapping issue was fixed for WC064.  They need to be re-ingested.

**Comment by cwulfman** [comment]
Figgy pulls the creator of a component from the component's `<origination>` element, if it exists; otherwise it defaults to the collection creator. For the example above (https://figgy.princeton.edu/catalog/0f6b93b2-e89e-4074-b069-9a55583a6519) there is no `<origination>` element in the EAD (nor is there creator information in the original MODS record), so Figgy is defaulting to the collection creator.  In another item from WC055 (https://findingaids.princeton.edu/collections/WC055/c0580) the component does contain an `<origination>` element, and it is correctly displayed in Figgy.

**Comment by tpendragon** [comment]
When this is fixed you should be able to just refresh the metadata, shouldn't have to reingest.

**Comment by cwulfman** [comment]
@tpendragon my earlier comment was correct but irrelevant, as it turns out, and I've deleted it.  The problem is not with the processing but with the metadata.

**Comment by cwulfman** [comment]
The creator/photographer issue has been resolved.
