### ISSUE TITLE
Update the EligibleItemService not to fail when there are no items

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4131]
## Backtrace

    line 11 of [PROJECT_ROOT]/app/resources/cdl/eligible_item_service.rb: item_ids
    line 85 of [PROJECT_ROOT]/app/resources/cdl/charge_manager.rb: item_ids
    line 19 of [PROJECT_ROOT]/app/resources/cdl/charge_manager.rb: eligible?

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/65767199)

**Comment by christinach** [comment]
There are bibids for example: 4719556 (Special Collections - Cotsen Children's Library), 4133649 (East Asian Library - Rare Books) that have no items and they require a Reading Room Request. If we are considering to have CDL for rare books we should think of a way how to handle the EligibleItemService since for most of them there are no items to be checked out to a cdl patron_group.
