### ISSUE TITLE
why aren't the individual items for grounds and buildings showing up in figgy?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4221]
Collection of individual items (none actually showing up, but numbers still there in collection information): https://figgy.princeton.edu/catalog/a3d75c94-2eee-47b7-b193-3b09eb9b13e7

MVWs of these: https://figgy.princeton.edu/?f%5Bhuman_readable_type_ssim%5D%5B%5D=Multi+Volume+Work&q=AC111

Why can't we view any of the items (why aren't they found?). @escowles is this a result of something that had to be done to create the MVWs?

**Comment by tpendragon** [comment]
The volumes are added to the collection, but the MVWs aren't. Search results hides volumes (because you'd get a bunch of "Vol. 1", etc.)

**Comment by escowles** [comment]
This is really a continuation of https://github.com/pulibrary/figgy/issues/3815 — and I think we have a couple of options for how to move forward here, in approximate order of how difficult I expect they would be to do:

1. Sync the MVWs over to DPUL and deal with them at that level (and use ordering and structure for description within the MVWs)
2. Add some logic to figure out that we want to sync the members of these MVWs (not sure if there's a way to identify those now, or if we'd add a new property, or something else)
3. Revisit the modeling and consider making these collections instead of MVWs (which would solve the DPUL problem, but bring back the problem from #3815) — we have several cases of photo albums and photograph collections with similar issues, so being able to do this would help more than just this collection
4. Revisit the decision to avoid item-level description of these items in the finding aid

**Comment by kelea99** [comment]
Thanks, @tpendragon and  @escowles. Ok, so:
1. we could, but is order/structure really appropriate for yet more description if we are using it already as a discovery tool for each item in the MVW? I dont see it as ideal or working with every use case. I may be wrong.
2. Can we talk a bit more about this possibility?
3. If it helps: as a work around, we were able to get around the photograph collections  in Western Americana by treating the photo album itself as an individual work with a MARC record. all the individual photographs are still FA items. 
4. This seems the more reasonable way forward, since this is a big reason why we are evisiting problems with ingest and metadata for more than one collection at this point.

**Comment by tpendragon** [comment]
Oh I see. You want the items individually discoverable in DPUL. Yeah, number 4 please. Number 2 we'd have to add a way to say "yeah these are members but make them discoverable and make them sync"

**Comment by kelea99** [comment]
Good to know and thank you! I'll try my best, @tpendragon. @escowles and @cwulfman let me do a test to see how adding the extra stuff to order/structure may look and we can go from there for this particular project, just to get the migration done for it and forthcoming postcards. standby

**Comment by cwulfman** [comment]
This is part of the general MVW issue, and not PUDL per-se.
