### ISSUE TITLE
[Figgy/production] MultiJson::ParseError: 783: unexpected token at 'Record 10450683 not found or suppressed'

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4253]
## Backtrace

    line 95 of [PROJECT_ROOT]/app/models/remote_record.rb: jsonld
    line 83 of [PROJECT_ROOT]/app/models/remote_record.rb: attributes
    line 14 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister/apply_remote_metadata.rb: run

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/67105549)

## Technical Implementation

RemoteRecord should not error when it gets a suppressed record back.

**Comment by christinach** [comment]
remote_record.rb 95 jsonld(...)

93 
94     def jsonld
95       @jsonld ||= MultiJson.load(jsonld_request.body, symbolize_keys: true)
96     end

rescue when a record is not found or is suppressed. Bibdata returns: 'Record `resource_id` not found or suppressed'",

**Comment by christinach** [comment]
Contact Nicholas and Liza from https://library.princeton.edu/unit/reserve-and-resource-sharing-services. Inform them that the specific ids fail to ingest. Additionally find the pdfs in the figgy worker `/mnt/illiad/cdl_scans/ingesting` download them in your local machine and provide to them the title of the pdf so that they can find them and re-ingest them with the correct <bbid>.pdf. 

In the case of `10265735 ` and `72122432 ` I had already checked voyager and let them know that these records do not exist in voyager.

**Comment by christinach** [comment]
Per Nick's request I deleted 10265735.pdf because somehow it made it through the scans and renamed 72122432 -> 7212432.pdf

**Comment by hackartisan** [comment]
A couple of things to add based on running this week. When resolving an error from a job like this it's helpful to also delete the job in sidekiq to keep the error from occurring again.

Also, when renaming the file for CDL, the file needs to be moved up a level, out of the `ingesting` directory. See https://github.com/pulibrary/figgy/blob/88e37c0fcdd42dbf39e65d772338e155f0a63d1d/app/resources/cdl/automatic_ingester.rb#L16-L20
