### ISSUE TITLE
Add a date facet to Figgy

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4254]
The VIrtual Reading Room (VRR) [functional requirement](https://docs.google.com/spreadsheets/d/1z8Z_k42inQtAHarRrOfjMGzSwnYoCpIOr0J99RL6kqk/edit#gid=0) R006 that "components be searchable by component name, collection name, date, etc."

This metadata should currently be in the index, however to meet this requirement, it's been requested that we add a date facet to Figgy's search interface. 

## Implementation Details

* Use the "created" field for this facet.
* If possible, implement this facet with a slider (such as the [blacklight_range_limit plugin](https://github.com/projectblacklight/blacklight_range_limit)).
* This facet will just pull in the value of the start date, where there is otherwise a date range.

**Comment by hackmastera** [comment]
date_created is a string field which according to our tests expects to handle values such as "circa 1865" and "1941-1985".

In order to facet these will need to be normalized into year-only dates. In order to use blacklight-range-limit they will need to be sortable, integer values.

Orangelight uses blacklight-range-limit by pulling the start date from the 008 ([logic here](https://github.com/pulibrary/marc_liberation/blob/493949186cbb8cf5f6bb888aced888cfca149051/marc_to_solr/lib/princeton_marc.rb#L59-L66)) And in Figgy that is the same logic used to populated "date created" (logic [here](https://github.com/pulibrary/figgy/blob/3c3283c47c3154398b55ddb83e7f025060686fef/app/services/pul_metadata_services/bib_record.rb#L19) and [here](https://github.com/pulibrary/figgy/blob/3c3283c47c3154398b55ddb83e7f025060686fef/app/services/pul_metadata_services/bib_record.rb#L86-L88)).

For finding aid items, figgy pulls the display date into the `date_created` field but we pull a normalized iso8601 date into the `created` field. It would be preferable to use this normalized value as the source for the facet.

Implementation proposal:

1. Create a new Valkyrie field on ScannedResource called `pub_date_start_sort` (this is what it's called in orangelilght) to use as the facet field. Then:
   1. Either pull the value during metadata synchronization.
   1. Or at index time check the source metadata identifier. if it's a bib number copy the `date_created` field into the new facet field. If it's a component ID extract the year from the `created` field.

**Comment by tpendragon** [comment]
I have a super fuzzy memory of bibdata providing two date fields, one normalized. Is that not the case?

**Comment by tpendragon** [comment]
@hackmastera I don't think we actually use `PulMetadataServices::BibRecord` and haven't in a long time. I think we just pull the data from the JSON-LD serialization here: https://bibdata.princeton.edu/bibliographic/5317891/jsonld

**Comment by hackmastera** [comment]
Well, look forward to a refactor ticket.

Then it sounds like we can expect created to always have a value we can use here.

Option `ii` above is what you've just said -- an indexer that pulls the `created` value.

**Comment by tpendragon** [comment]
We might have to separate the start/end dates into two fields, right now it combines them if it can.

**Comment by hackmastera** [comment]
We'll plan to just pull the start date, as is done in orangelight.
