### ISSUE TITLE
"LAE_to_ingest" upload of Hellenic Ephemera poster box is extremely slow

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4302]
Beth in the studio is trying ingesting box 3 of  Hellenic ephemera posters (03_32101103418586) and is uploading via “lae_to_ingest”. It went from saying it would take about 20 minutes and is now saying “About an hour” for the time estimate.

**Comment by kelea99** [comment]
Update: that folder is now uploaded.

**Comment by hackmastera** [comment]
👍 Okay to close @kelea99 ?

**Comment by kelea99** [comment]
it is if you see nothing wrong with ephemera ingest, @hackmastera !

**Comment by hackmastera** [comment]
I see an `IngestLaeFolderJob` which started at 9:26 and completed at 9:35. Presumably this was started via the `ingest_disk_files` rake task. The initial report is from earlier than that (at 8:44) but I don't see any errors.

I'm not really sure about this message saying how long it would take because I don't see any progress bar functionality in the rake task. I think we'd need more information about the problem in order to troubleshoot further, but since the ingest was successful I'm inclined to close the issue. Please reopen it if you have more details you think we should look at!

**Comment by kelea99** [comment]
Sounds good. I'll let beth know, and if it is a problem again Ill reopen the ticket.
