### ISSUE TITLE
Figgy is slow to respond and just errored with "This website is under heavy load (queue full)"

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4341]
What I did:
Searched in figgy via facets for "Patron Requests" and "Russian" languages.
was clicking "next" to review each item in this search selection. very slow to advance.
error:
<img width="1440" alt="Screen Shot 2020-12-04 at 11 56 44 AM" src="https://user-images.githubusercontent.com/45043014/101191731-0d9e4500-3628-11eb-8c0b-1f48d17ecd78.png">

**Comment by tpendragon** [comment]
This happens when passenger is overloaded with requests, usually from a bunch of manifest requests from DPUL. For it to be happening right now there would have either had to have been a bunch of saves in Figgy at the same time which are in DPUL collections, or a DPUL collection was made or reindexed?

**Comment by tpendragon** [comment]
To fix this with infrastructure we'd have to either make more figgy boxes until it can keep up, or add a `figgy3` which just serves manifests, leaving the front-end to other boxes.
