### ISSUE TITLE
Figgy needs to be verified by Google

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4478]
Users still get the message that the app isn't verified when using google drive.

https://github.com/pulibrary/figgy/issues/3788 was closed with a note that we don't need this anymore after upgrading browse everything, but that doesn't seem to be the case.

**Comment by jrgriffiniii** [comment]
This is currently blocking https://github.com/pulibrary/figgy/issues/4525 from being advanced.

**Comment by jrgriffiniii** [comment]
A YouTube video demonstrating the usage of Google Drive integration with Figgy, along with a description of the behavior of the application (in relation to Google Drive) was required in order to ensure that Figgy is verified by Google. This has been submitted for review, and the Trust and Safety team from Google should be expected to provide a response in, at most, 5 days.

**Comment by jrgriffiniii** [comment]
I have just been notified that this is blocked due to `figgy.princeton.edu` domain not being verified with the Google Search Console service.
