### ISSUE TITLE
Bulk ingest of Lapidus items is using the directory name as a source metadata identifier when it should be a title

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4588]
See https://figgy.princeton.edu/catalog/70de2cc7-d83b-4e70-93b2-6a995ceeb564

I have a fuzzy memory of this being because the response of Pulfalight was different from Pulfa somehow, but I'd have to look again.

**Comment by kelea99** [comment]
This happened before in April 2021 for a bulk ingest.  It was solved by putting two underscores for the file naming convention (example: "Lapidus 4687988" or "Lapidus__4687988"). the title with two underscores, etc. wouldn't trigger the PULFA ID.

**Comment by kelea99** [comment]
@roelmoon , Ill contact toya about this, but want to make sure its a recent drive and all items have the same problem.

**Comment by kelea99** [comment]
@roelmoon can you double check the filenaming on the studio server to ensure that the new naming convention is being used? Looking at Figgy now and we have consistent ingest as source metadata identifiers since it was first reported in April. 
479 records affected. 
Creation date range for affected records: 04/07/21 08:39:36 PM UTC - 07/27/21 06:45:18 PM UTC.

**Comment by kelea99** [comment]
@roelmoon and I are testing.

- double underscore (__): Still ingests as source metadata identifier in bulk ingest
- single dash (-) between NAME and BIB: Still ingests as source metadata identifier in bulk ingest
- nothing between NAME and BIB: Still ingests as source metadata identifier in bulk ingest
- nothing between BIB and NAME:  IT WORKS!  https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=4726349Lapidus

Closing ticket, @tpendragon, unless you would prefer to fix this . We can live with the items currently using the directory names as source metadata ids.   The source metadata identifiers are all going to be added by SC folks to the entirety of this collection anyway during their QC, so it does not affect workflows on our end that they are ingested in this way. 

KEL writing to Toya about this.. any Hard drives already sent to PUL we will ingest as is. moving forward we are requesting the new filenaming convention for this project, due to title only ingest need (the MARC records are suppressed by Don and Steve F. for this collection).

**Comment by tpendragon** [comment]
@kelea99 If y'all are doing work fine then it's okay. I suspect this will happen at random intervals for anything with an _ in the name though.

**Comment by kelea99** [comment]
Its good to know, though. I will at least get the word out about title only ingest naming conventions.
