### ISSUE TITLE
Projected growth of categories on logged-in front page / reorganization?

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#468]
I noticed none of the main sections on this page have more than 1 or 2 items. Is it worth consolidating some of these? Or reorganizing the page in some way? Particularly if we start adding reports as proposed in https://github.com/pulibrary/figgy/issues/465#issuecomment-339323100 

This is on staging; I don't think I'm an admin on prod so I'm not sure how it looks there.

**Comment by escowles** [comment]
I think that some categories will wind up with only one item (Books and Collections), some will have a few items (Geo), and some might wind up having a bunch of items (there are ~15 ephemera projects).  So I agree it's worth thinking about reorganizing the content.

* It looks like the page is wide enough to handle about 5 items per row, so having multiple sections in a row would be an easy way to fit more items per row.
* If we do have 10+ ephemera projects, we may want to display them in a list or table instead of using such a large box for each project.
* There is also a lot of whitespace, which could be reduced to increase the information density of the page.

**Comment by hackmastera** [comment]
What if we combined Books and Geo into "Add new resource" with a nice button for each type of resource?

Then collections and ephemera projects could each have a table-based display with an "add new" button as part of its header maybe?

**Comment by hackmastera** [comment]
close in favor of https://github.com/pulibrary/figgy/issues/894
