### ISSUE TITLE
Resources updated in Pulfalight should update their metadata in Figgy automatically.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4774]
Metadata is often revised in Pulfalight and we have external projects like Shakespeare and Company which use the JSON-LD that Figgy provides that's a view of that metadata. We need to keep the Figgy metadata in sync with the remote source.

**Comment by tpendragon** [comment]
Historically we've used a pull model for this - now all of our sources are us and under our control in some way. I'd like to use a push model so that remote services tell Figgy "hey this changed".

Options I see:

1. `/identifiers/:identifier/update` - Notify Figgy an identifier is updated.
2. GraphQL mutation
4. GraphQL pub/sub
5. WebSub (https://www.w3.org/TR/websub/#h-note-0)

Something else...?

**Comment by sdellis** [comment]
My colleague at the Princeton Development Office used WebSub in 2008 (then called "PubSubHubbub") to sync a number of our applications. I definitely think the Pub/Sub model is the way to go for this type of use case, so I'd say #4 seems most appropriate, and allows us to easily sync future systems with the same infrastructure. 

Not sure what is involved in #1. Is the idea that it's just an API endpoint that waits for some system to send it an ID to then update?

I'm also a bit wary of GraphQL pubsub as I feel like we may have instances where we will want to sync systems in which GraphQL is not involved. It also seems a bit underdeveloped based on the docs.

I assume each of these solutions will also require some plugin/code to be written for ASpace that "publishes" data updates, correct?

**Comment by tpendragon** [comment]
> I assume each of these solutions will also require some plugin/code to be written for ASpace that "publishes" data updates (or in the case of #1, makes an API request), correct?

We update from Pulfalight - my intention was to just have Pulfalight ping Figgy after an index job.

**Comment by tpendragon** [comment]
For 4 I'd have to look at the spec more than the cursory glance I gave it.

How would we handle Figgy having to be both the "Hub" and "Consumer" if we went that route?

**Comment by hackartisan** [comment]
Option 1 seems quickest to implement. Do the benefits of pubsub outweigh that consideration? Assuming pulfalight runs a background job, and the figgy endpoint also kicks off a job, I think we have a very low potential to lose these events.

**Comment by hackartisan** [comment]
I like the idea of a wildcard, also fine with a separate endpoint. this seems like a case where on the figgy side it might be worth looking into using async for the network IO, so I don't think we should send each as its own request.

**Comment by hackartisan** [comment]
endpoint `/resources/update_metadata` expects a body like `{ source_metadata_identifiers: [...] }` or `{ archival_collection_codes: [...] }`. For this ticket implement the code path for `archival_collection_codes`.

Implementation

- I get a list of things
- I kick of a job for each thing in the list
- That spawns a job per figgy resource that actually fetches the record/s from pulfalight
- See if metadata changed somehow before we persist to prevent needlessly re-preserving.
  - Note that the source metadata sync happens in the change set persister; we would have to compare up front somehow
- Use batches?
  - Would let us see the hierarchy of these jobs.

Example:

- I update C0001_c01 in ASpace
- Pulfalight hears that C001 changed.
- Pulfalight reindexes the full collection, because it has to, that’s how Pulfalight works.
- Pulfalight posts to figgy /resources/update_metadata with body { archival_collection_codes: [“C0001”] }
- Figgy hears the request, spawns a job for updating per collection code, returns “202 Accepted”.
  - queue low priority
- That job gets all resources which have that archival collection code, and spawns a metadata refresh job for each of those resources.
- The metadata refresh job should try to update, if nothing changes then don’t persist.
  - This metadata refresh job should be in the low priority queue.
- How many jobs per metadata update?
  - End up with one job per resource to be updated.
