### ISSUE TITLE
Disallow Collections on Child members within Parent Records

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4833]
Somehow resources which are children of other resources are still able to get added directly as members of a collection. Any resource which is a child of another resource should not be able to be a member of a collection; this causes them to be double-indexed in DPUL.

We have seen this happen with the ealtoc collection. It would be useful to have a meeting with Tom to understand his ingest workflow, in case that could give us some hints.

Related issues and previous work:
- Corollary DPUL ticket is pulibrary/dpul#1274
- Remove collection when a resource is moved into a child #5695
- Rake task to remove collection for members that are child resources: https://github.com/pulibrary/figgy/blob/main/lib/tasks/migrate.rake#L126
- Several PRs were created addressing https://github.com/pulibrary/dpul/issues/1420
- Add "show children" toggle to search results: https://github.com/pulibrary/figgy/pull/6002

## Sudden priority justification
Repeatedly debugging these issues takes developer time, we'd like to solve it so we aren't pulled away by this again.

## First Step

Look at bulk ingest logic to see if there's a gap in there allowing child members.

Meanwhile, Kim's gonna ask Tom to record himself doing this.

**Comment by hackartisan** [comment]
I asked Tom what ingest directory he uses, and he told me he has his this issue with items in ingest_scratch/EAL/Chambit. So I messed around with one of those (copied to ingest_scratch/anna) but I was unable to replicate. I also didn't see anything in the code that looked suspicious. Tom said he hasn't done any bulk ingest since we repaired the ealtoc collection. He will let `@dls` know when he next does a bulk load so that one of us can pair with him to see his ingest workflow. Until then this ticket is blocked.

**Comment by hackartisan** [comment]
Once Tom is ready to pair with us, we should take notes (maybe record) and then see whether the issue recurs.

**Comment by tpendragon** [comment]
Tom demo'd this for me today, I'll attach a recording soon. All he does is go through bulk ingest, and uses "Complete when Processed"

**Comment by tpendragon** [comment]
The demo showed us that he just goes through the bulk ingest workflow. We're going to close this, and if it happens again we're going to reopen it and then really dig into bulk ingest and see what we could have possibly missed.
