### ISSUE TITLE
Preservation master file errors during characterization

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4846]
[Figgy/production] NoMethodError: undefined method `mime_type' for nil:NilClass

The target_file is nil and doesn't have a mime_type: https://github.com/pulibrary/figgy/blob/a7216806b5c5809eacb59b8a62980bcec5c82d8f/app/characterization_services/null_characterization_service.rb#L24

What should happen in this situation? Should characterization short-circuit?

Need to look more closely at the item / use case that triggered this error. It looks like a CDL ingest (in that collection), but done manually? The page images did successfully generate -- how? Also, it's part of a multi-volume work.

This scenario isn't documented in the CDL Best Practice doc: https://docs.google.com/document/d/1zX-V93TGy-2U2AF-cZb6GBrrz-J6onF1yo8UgMoSzes/edit#

We need to document when we use various pcdmuse values, and what implications they have for workflow events.

## Backtrace

    line 20 of [PROJECT_ROOT]/app/characterization_services/null_characterization_service.rb: valid?
    line 9 of [PROJECT_ROOT]/app/jobs/characterization_job.rb: block in perform
    line 94 of [PROJECT_ROOT]/app/adapters/indexing_adapter.rb: block (2 levels) in buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/83248459)

**Comment by tpendragon** [comment]
Two questions:

1. Why did the NullCharacterizationService get called in this case?
2. A NullCharacterizationService shouldn't blow up if it's given a PreservationMasterFile. Use `#primary_file`

**Comment by hackartisan** [comment]
The Characterization job was running on

fileset: https://figgy.princeton.edu/catalog/0c9a91d4-9549-422f-8193-83cff9d4f691, title: 9919354213506421-commentary.pdf
parent: https://figgy.princeton.edu/catalog/be16e338-1b8a-43f9-a4d9-83ed17032157
parent's parent (MVW): https://figgy.princeton.edu/catalog/19c83d65-e3fc-4219-8883-f14f3ef4e811

The file is the preservation file pdf. All page images appear to have generated as desired and the viewer looks good. The parent items both say 54/55 files processed.

With these pdfs, they are initially ingested as original files, and they are changed to preservation files during derivative generation 
https://github.com/pulibrary/figgy/blob/b19cd2d19a69147783bb67c5a5282083eecfc007/app/derivative_services/pdf_derivative_service.rb#L132

This implies that the error here occurred due to someone attempting to regenerate derivatives for this pdf. This is something we want to allow, and the proposed fix of using `primary_file` in the NullCharacterizationService should fix it. Once that's in place we should be able to regenerate on this item to clear the error.

**Comment by hackartisan** [comment]
Deployed the fix and regenerated derivatives on the pdf. It took about 5 minutes. Everything looks good, except the resource again says 54/55 items processed.

**Comment by hackartisan** [comment]
Since we don't have a pattern of these I went ahead and manually changed the preservation_status for the file set, as seen in https://github.com/pulibrary/figgy/blob/bc4bc859783b3b455d30b03d1044bf48f54e2dcd/app/jobs/create_derivatives_job.rb#L9
