### ISSUE TITLE
Select for Ephemera Folder Subject Select on Edit scrolls to the bottom

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5234]
It scrolls to the bottom for edit, but not for new subjects.

**Comment by hackartisan** [comment]
It tries to jump to the most recently added entry, but often they are nested and collapsed.

**Comment by hackartisan** [comment]
We messed with this for a while but weren't able to a good fix. Some considerations and things we tried:

- The nested options are a local enhancement.
- The "open" event appears to run the focus reset code after it executes, so when we tried to attach an event to it sending the focus back to the top, it didn't take.
- We couldn't access the Result prototype in order to override the `ensureHighlightVisible` function.
- After reading about adapters (e.g. https://select2.org/advanced/default-adapters/results) we tried an approach similar to https://github.com/select2/select2/issues/4436#issuecomment-227692224 by running the following in the browser console but it didn't work. Perhaps we would need to bring in the code via a javascript bundler rather than a CDN to make this kind of change: 

```
$.fn.select2.amd.require(['select2/results'], function (Result) {
    Result.prototype.ensureHighlightVisible = function () { }
})
```

We've decided to close this issue for now since we've spent a lot of time on it without yet knowing the bug's impact on users.
