### ISSUE TITLE
Get to Rails 6.1

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5275]

**Comment by tpendragon** [comment]
I did a spike. Things I found:

- [ ] We have to do #5271, #5270, #5269, and #5267. Probably #5268, but I didn't run into that.
- [ ] We have to update Reform to prevent a Rails deprecation message spamming. `valid?` and `validate` APIs changed a little, so we have to fix a couple of tests and the skip validation feature. See https://github.com/pulibrary/figgy/commit/46a9d8f8c6946b3c23057b3fd6a6defd47d6b66b and https://github.com/pulibrary/figgy/commit/a88a07842fa1925c218141728b7efb6cf0eacd88#diff-362d8fca552a19c801df92b4b8242a2477d22488a2495387e6871fff145d60b1R57. I expect there will be other failures, we'll have to do some QA too.
- [ ] We have to use a branch of Browse Everything to support Rails 6.1. Since we've been on a branch this whole time I did it in yet another branch. I don't think BE 2.x is going to ship: https://github.com/pulibrary/figgy/commit/6c2ef4a6e2252070944cdf204b5ad0baddecf012#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR16
- [ ] We have to update Datadog - I think we should remove the InstrumentedAdapters, as the API has changed a lot and I couldn't easily find a way to convert it over. Over the years we haven't used those metrics anyways. See https://github.com/pulibrary/figgy/commit/93e5f1433bc71b68b7099d2a5def3508ce76715e. Make sure to remove InstrumentedAdapter references from the specs too.
- [ ] We have to run a migration for ActiveStorage, it's done via `rails active_storage:update`. Rubocop will complain about the migrations, we should ignore them.
- [ ] Fixture_file_path is a little different. I think the fix is in rails_helper to set `fixture_file_path` instead of `fixture_file` and then fix the specs that fail to include `/files/` Some of those changes are here: https://github.com/pulibrary/figgy/commit/19abc29e53034bd5f16770dcee4b790835de90a2 and here: https://github.com/pulibrary/figgy/commit/0c8bda9f9a4a88681871752015e2630c55da511c also https://github.com/pulibrary/figgy/commit/1d1bf3ca1dd4b2c70993120083ca02bb8c302319


Alll of that in the trial branch resulted in 10 failing tests.
