### ISSUE TITLE
Cloud derivates for raster files are not saved in AWS

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5377]
The root error message is:
 Aws::S3::MultipartUploadError: multipart upload failed: undefined method `read' for #<IngestableFile:0x00007f0e58b88c20>
https://app.honeybadger.io/projects/53391/faults/84134442/01GAVHVEEMF8G8135VC6MSAG16?page=0

**Comment by tpendragon** [comment]
This broke because we updated Shrine when we updated Rails. In the old version, put used to just require something that responded to #path (https://github.com/shrinerb/shrine/blob/0bda9f969a6bd610fdbc93041120dda81b5a7d86/lib/shrine/storage/s3.rb#L288), now it requires an IO (https://github.com/shrinerb/shrine/blob/v3.4.0/lib/shrine/storage/s3.rb#L222-L230)
