### ISSUE TITLE
Redesign the preservation status indicators on the resource show page

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5528]
Existing Display: 
![Screen Shot 2022-11-17 at 12 27 13 PM](https://user-images.githubusercontent.com/2806645/202552747-5b7a2186-e754-423c-999f-1d9ea495e83d.png)

The goal of this display is to quickly convey the current status of preservation on a resource in a way that reflects our preservation policy.

**Comment by tpendragon** [comment]
There's also a display in the members list:

![Screen Shot 2022-11-29 at 8 50 21 AM](https://user-images.githubusercontent.com/2806645/204591739-dedd1d8f-1610-4d63-9459-451c235f9dba.png)

We think it would be useful to show the cloud fixity status here too, if we're showing the local fixity status.

**Comment by sdellis** [comment]
For the first part of this ticket, here's an idea. Thoughts?

![resource-fixity.png](https://images.zenhubusercontent.com/5cba15f2e89c9c3b0c58e0d1/d92023a7-51b7-4dbb-9078-0443dd915127)

I was looking for our Preservation Policy, to make sure that it's reflected in this design as per the goals of this ticket, but I can't find it. Do we have a Preservation Policy? I was particularly interested in whether the Local and Cloud fixity are run simultaneously for a resource, or if they are independent and randomized (i.e., cloud fixity is run, but local may not be checked for quite some time or at all, and vice-versa).

**Comment by hackartisan** [comment]
I'm not sure about a Preservation Policy. But the checks are run independently. For cloud fixity we run a random selection of resources per day. For local fixity we (plan to) run the least-recently-checked resources as continuously as we can.

**Comment by hackartisan** [comment]
For this design, I like that it adds more language to explain what the numbers mean. I also like that the icons give a more wholistic sense of the status. I like the addition of the link to repair. I'm not entirely sure about the use of the word "originals" here. And from both an implementation and a user standpoint, I don't know exactly what this date means, since the files may have been checked on different dates. It may help to have what you called a Preservation Policy, or just user-facing documentation of how we check fixity.

**Comment by hackartisan** [comment]
work up a mockup for a “Health Report” panel. Current health checks will be on 1) Local Fixity and 2) Cloud Fixity. In the future, we can look to add 3) Derivatives Generated.

**Comment by sdellis** [comment]
Mockups for a Preservation Status notification and health report panel/modal. (Please note that these mockups are intended to be fast iterations to convey the gist. They are not "pixel-perfect" final renderings.)

![HealthReport-Healthy](https://user-images.githubusercontent.com/609368/210654266-135f9cd6-c3e3-4743-b415-bee02a4ea246.png)
![HealthReport-NeedsAttention](https://user-images.githubusercontent.com/609368/210654271-93ddded3-3269-4a64-843e-118dac024bb3.png)
![HealthReportModal](https://user-images.githubusercontent.com/609368/210654274-8079e7cd-8095-4d8a-b696-c8f6a1d10b41.png)

**Comment by hackartisan** [comment]
I think the health report looks great! I like the icons and the button. Is the destination for that button a different issue?

The wording is still a confusing to me, I don't know what it means for the files to be the same as or different from the ones previously checked on a given date. For example, if there are 3 file sets, on a resource, there would be 3 preservation objects for the file sets plus 1 for the resource. The FixityRequestor randomly selects a bunch of preservation objects to check fixity on. So these 3 files (plus the resource metadata itself) could have been queued for checks on wildly different dates.  What is the "as of" date? and what is the "previously checked" date?

**Comment by sdellis** [comment]
@hackartisan I understand this wording doesn't convey enough to the user about our preservation practice. For better clarity, perhaps _every_ fixity check Figgy has done on a preservation object (after the initial successful ingest) should be listed in this health report? 

* Fileset-ABC was checked for fixity on 1/03/23 and is healthy.
* Fileset-DEF was checked for fixity on  1/10/23 and [needs attention](). 
* etc...

**Comment by sdellis** [comment]
@hackartisan and I discussed this and decided that the best place for detailed information about the health of a particular file is in the File Manager. The Resource page will have a general "health report" that will just confirm that everything is healthy (or not). If there are any files that need attention, the "health report" will tell the user there's a problem with one or more files and provide a link to the File Manager to find and correct the problem fileset(s). Each fileset card will have an indicator of its health status and a "last check" date. Clicking through to the FileSet show page will have additional fixity/health information and options. Please see issue #5543 for those details.

**Comment by sdellis** [comment]
![HealthReportModal.png](https://images.zenhubusercontent.com/5cba15f2e89c9c3b0c58e0d1/978dac55-bcc8-42af-b9c6-c3daf9a257cd)

Link to find/fix goes to File Manager. Screenshot of File Manager error indicators coming soon.

**Comment by hackartisan** [comment]
This is looking nice to me; it would be good to also have a variant where the derivatives aren't healthy.

I'm still concerned that giving a date for the last fixity check could be misleading to users; they might think the whole resource was checked on that day when in reality the different files will have been checked on different days. Maybe it should just say, "for fixity check dates please see the file manager" with a link to that page?

there may also be some special cases around multi volume works here that we need to think about. In that case we'd need to direct folks to the individual volume resource show pages, and perhaps from there to the file manager for a given volume.

**Comment by sdellis** [comment]
![filemanager-fixity2.png](https://images.zenhubusercontent.com/5cba15f2e89c9c3b0c58e0d1/eb5be863-b3a0-4322-a601-1fb6d5aed328)

This is a first pass at error indicators on the File Manager page. I think this whole page could be redesigned but in the interest of getting this preservation work done, this mock-up is intended to be a way forward with minimal reworking. I'm struggling a bit with the indicator language since a file could potentially have problems with local, cloud, and derivatives and it would be hard to find space for all of them without extending the card element for that file and messing with the grid consistency. Also, it needs attention to color and icons, but don't want to go down that path until I get some feedback on the general approach.

**Comment by hackartisan** [comment]
I think this is looking good. The colors and icons and exclamation points all definitely call attention to the broken objects. This page would probably be the place to be able to list the last checked fixity date for both cloud and local fixity, if we want to add that. I'm also curious how "repair this file" works. Does it go to the file set page, where we have more info on what the options might be? Does it do something different for a fixity failure vs a derivative failure?

**Comment by sdellis** [comment]
@hackartisan thank you. I'm not sure this would be the appropriate place to list the last checked fixity date, but I'm curious about why you think that. Isn't the most important thing to the user that it gets fixed? "Repair this file" would simply fix the problem by regenerating derivatives, or re-preserving the master/primary file. If both local and cloud fixity are broken, then the user would have to re-upload the file. What other options would there be?

**Comment by hackartisan** [comment]
I'm happy to just have the date displayed on the fileset show page if we don't feel we need them in a list anywhere.

**Comment by tpendragon** [comment]
Create three implementation tickets:

1. Add indicators for health of a file, including fixity failures with the red outline.
2. Create this after our discussion, but it's "what does "Repair this file" do?
3. Add indicators for failed derivatives to the file manager, same red outline.

**Comment by sdellis** [comment]
Given that there may be several types of errors on a given fileset, that preserved filesets should display "preserved", and cards should remain the same size, here is a revision. The errors and warnings stack on top of each other below the thumbnail. They could potentially obscure the thumbnail if there are enough. I removed the color of the card outline that corresponds to the error or warning since they can be mixed.

One thing to note is that I'm assuming DLS is not notified of a fixity failure and that the user must contact DLS to resolve it. I think the easiest thing to do here is to allow the user to report it, sending a message with a unique identifier to a DLS queue so we can try to resolve the issue manually. Once it's reported, it displays "Reported" and is no longer actionable.

We will need to display the following error messages:

- Repairing Derivatives
- Repairing Local Fixity
- Repairing Cloud Fixity
- Derivatives Failed | Report
- Local Fixity Failed | Report
- Cloud Fixity Failed | Report

![filemanager-fixity5](https://user-images.githubusercontent.com/609368/236327234-d679073a-9156-43fd-a80b-818060def9f5.jpg)

**Comment by sdellis** [comment]
"Report" link will not generate events or save state. Clicking that link will generate a Honeybadger notification with the user's id, the filemanager page URL, and the ID of the problematic fileset. This will allow us to easily create a GitHub ticket with the click of a button.

**Comment by hackartisan** [comment]
Still to determine: What happens visually when you click the "report" button?

**Comment by sdellis** [comment]
The consensus is that, at a minimum, there will be some system notification to the user that the issue was reported. This may be a flash alert or animation that confirms it was successfully reported (or not). Th state of which files have been reported would not be saved on the server. 

Note: If state is not saved, it could be hard for a user to know which issues have been reported or not if there are a lot of errors in the Filemanager interface. We could mitigate this confusion by storing ids that have been reported locally on the client, saving the state at least for the duration of the user's session or until they clear their cookies.

**Comment by tpendragon** [comment]
This ticket is done when there's an implementation ticket.
