### ISSUE TITLE
Broken collection

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5648]
The "[Patron Requests](https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Patron+Requests)" collection appears to be broken, but I'm not sure how.

1. Paging through collection members raises an error.
1. Selecting facets within the collection raises an error.

Maybe there's a broken resource in the collection?

**Comment by eliotjordan** [comment]
It's resource: It's 5a110633-73ff-480e-ba19-bd9375ecbc51

**Comment by tpendragon** [comment]
In the past this has been because something's in Solr but not postgres. I grabbed the second page's JSON (https://figgy.princeton.edu/catalog.json?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Patron+Requests&page=2), parsed the IDs, and ran them through:

```
saved_ids = ChangeSetPersister.default.query_service.custom_queries.find_saved_ids(ids: ids)
irb(main):023:0> ids - saved_ids.map(&:to_s)
=> ["5a110633-73ff-480e-ba19-bd9375ecbc51"]
```

Checking the logs that got ingested earlier today. Looking to see if it was reingested, source metadata identifier is: 9952649933506421

**Comment by tpendragon** [comment]
d799c392-9bda-4157-93c6-6cf88cac6d6a was a reingest of the resource and seems to be working. I'll delete that record from solr.

**Comment by tpendragon** [comment]
I deleted the bad ID from Solr:

```
Blacklight.default_index.connection.delete_by_id("5a110633-73ff-480e-ba19-bd9375ecbc51")
Blacklight.default_index.connection.commit
```

I'm not sure how this sync issue happened. It was ingested at 3:52 on Monday, maybe some system event caused it?

**Comment by eliotjordan** [comment]
Looks good now.
