### ISSUE TITLE
Wireframe user optimized Virtual Reading Room path options

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5958]
There's been a lot of discussion about how to make the current virtual reading room experience more convenient for users and staff while still fulfilling any user validation requirements we might have. One of those options was #5845, but we decided InCommon hit too few of our users while being too complex to work with.

## Reasoning

Our vision is to allow global communities to engage with diverse collections, but some of our most unique collections are unable to be opened up because of copyright or gift concerns. We can open it up to more people by lowering the barrier to entry and making it easier to get a hold of our content in a way that still protects the institution.

## Current Experience

A user requests access through https://library.princeton.edu/special-collections/ask-us
A staff member gets them to create an Aeon account (https://library.princeton.edu/aeon/aeon.dll)
Staff member then creates a NetID guest account
User configures a password for that NetID guest account
Staff member associates that NetID with a specific collection they want to provide that user to.
The user logs in with that NetID information views the item.

## Experience Goals

A user should be able to go from "I want to see this item" to "I can see this item" with minimal (maybe even zero) staff interaction and as fast as possible. The primary metric for success here is time from "I want to see this" to "I'm seeing it"

## Guidelines

1. Users should have to agree to a usage requirement before accessing the item.
2. We should be able to keep track of which items an individual account uses (much like we do in Aeon)
3. We do NOT want to store passwords.

## Background Info

* Right now everyone who requests a VRR item creates an account in Aeon. Historically we haven't been able to get API access to Aeon - that's expected to change in the next month. API is here: https://support.atlas-sys.com/hc/en-us/articles/360011918933-Aeon-API
* Anyone who asks for access right now is provided it. There's no "should you have access to this" decision process, and we want to keep that.

### Text Workflow

1. A user requests access to the item and enters their phone number.
2. A text is sent to the user with an access code
3. The user enters the access code
4. Figgy either creates or logs the user in to the account associated with that phone number.
5. Figgy displays a click through
6. The user clicks "Access", it's logged, and they're allowed to view the item.

### Email Workflow

The same as above but it's an email instead. Less guarantee of a real person behind, but also probably free to implement.

### Aeon Workflow

1. User requests access and enters their Aeon Email (or creates an account.) Creating that account takes care of the usage agreements.
2. Figgy validates that the email is in Aeon and sends an authorization code to their email.
3. User enters that authorization code
4. Figgy creates a request for that item for that user in Aeon and fulfills it, the user's able to see the item.

### Click-Through Workflow

For VRR items there's a click-through and then they get to see it.

## Fulfillment Criteria

To evaluate our comfort and provide some options to OGC and special collections we should have some rough wireframes of what the experience is like for an unregistered user to go through these process options.

## Priority

As policy and active discussion is going on I'm marking this as sudden priority for a maintenance cycle. I've estimated 6-8 weeks, giving us time to clear out of Valkyrax.

**Comment by sdellis** [comment]
Without some type of login, how will we track which items an individual uses? I think there needs to be some kind of authorization to do this. I like the phone number login as it seems like it makes for quick access but still allows us to monitor their use.

**Comment by tpendragon** [comment]
> Without some type of login, how will we track which items an individual uses?

Yeah, I think that option (click through only) is about us considering if we can get away not tracking users that granularly.

It's more awkward, but I'm warming up to the Aeon option if only because it means we avoid having to write a bunch of reporting logic in the future - all requests for special collections are in Aeon. So just seeing the variety of options from a user perspective might help us decide what trade offs to make

**Comment by sdellis** [comment]
Aeon sounds like a good option for moving forward. And it would be great if we don't have to track the use like that.

**Comment by hackartisan** [comment]
Great ticket, with all these details on motivations, use cases, and pros / cons. Love seeing the success metric! It would be cool to record the current value of that metric and the "acceptably low" value.

**Comment by tpendragon** [comment]
Note: We moved Aeon, and we should have API access now.

**Comment by sdellis** [comment]
Draft workflow wireframes for review:

1. [Example One (SMS Text)](https://xd.adobe.com/view/7f46d23e-9e6f-4e51-bf6e-20680343ed3a-2a15/)
2. [Example Two (Email)](https://xd.adobe.com/view/7f46d23e-9e6f-4e51-bf6e-20680343ed3a-2a15/screen/0946c58d-77c3-4e6c-b986-306feaec9ff5)
3. [Example Three (Aeon)](https://xd.adobe.com/view/7f46d23e-9e6f-4e51-bf6e-20680343ed3a-2a15/screen/d481636c-6a24-4981-97d4-fe077cca17ff)
4. [Example Four (Click-through)](https://xd.adobe.com/view/7f46d23e-9e6f-4e51-bf6e-20680343ed3a-2a15/screen/43ab32e4-4528-4af9-9281-c7c8847d0073)

Two notes to be aware of:
1. To my knowledge, the Click-through workflow cannot not satisfy the second guideline that we should be able to keep track of what resources a user uses
2. The Aeon API does not support User Creation. Although there is an [Authentication section to the API](https://support.atlas-sys.com/hc/en-us/articles/360011918933-Aeon-API#h_01GE81A890VQ37AZGPBAEGZYD4), I believe this has to do with authenticating to the API, not end users authenticating to Aeon.

**Comment by sdellis** [comment]
Some more thoughts on the Aeon approach:

If a user enters their email address, we can check Aeon via the API to verify that they're registered, create a "Request" for them (that goes into a custom VRR Queue), and provide instant access. We can also query all VRR requests by a single user, and we can also query all the VRR requests in the Custom Queue, which can be filtered by date. This is all through the Aeon API, so we can create a separate interface for querying VRR requests, presumably to get statistics/analytics (i.e., what resources are popular) or to investigate abuse/use that violates our policies.

All this is to say that if we go with one of the other workflows, we will need to build a backend that supports a queryable record of user accounts, the user's registration date, date of acceptance of terms, and a list of VRR content ids that they requested. Since our terms may change, we will need to be able to re-ask the user to accept the terms if they have not done so since the change.

One final note is that implementing the feature that checks if a user is already registered via Aeon would greatly improve the Request Workflow of the current Finding Aids site as well because it would not require the user to login and leave the content page before they can submit a request.

The one issue I see with the Aeon approach is that there is no way to register a user without sending them to the Aeon site to create their account. If there was a way to redirect them back to the referring page, this option would be both easiest to implement and a good user experience, in my opinion.
