### ISSUE TITLE
Adjust the placement of sorting controls for DataTables within Ephemera Projects

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#659]
The controls to sort by a certain field should be alternated, and the Box number should consistently be the default field by which the table rows are sorted for any given Project.

**Comment by tpendragon** [comment]
What does "the controls to sort by a certain field should be alternated" mean?

**Comment by escowles** [comment]
![labels](https://user-images.githubusercontent.com/856924/33779584-7c50a264-dc1b-11e7-8e0a-8f8ead6c7dac.png)

Because of the spacing between the label and the sort control, it's easy to get confused about which sort control goes with which label.  The control and label should be right next to each other.

**Comment by tpendragon** [comment]
That's funny, while I was clicking around I was totally confused too. Sounds good.
