### ISSUE TITLE
Show bibid in file manager

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#669]

**Comment by sdellis** [comment]
I imagine this is so that the Digital Studios can easily find the corresponding folder to do Q&A (i.e., check and make sure that the correct images are there)?  

The problem is that the manifest doesn't contain the bibid. Can we add it as a metadata field to the manifest? 
```
"metadata": [
    {"label": "BibID", "value": "3149645"}
]
```

Another approach would be to include a link to the item in the catalog in the manifest, under the `related` property? I imagine this may have uses outside of the Filemanager to point people back to the catalog record and associated services there.
http://iiif.io/api/presentation/2.1/#related

(Of course, it's possible that there is no Bibid in some circumstances.)

**Comment by escowles** [comment]
@sdellis The BibID should be in the metadata hash as "Source Metadata Identifier":

```
"metadata": [
  {"label": "Source Metadata Identifier", "value": ["4609321"]}
}
```

Or it may be the PULFA component ID, either way, it would be good to display it for context.
