### ISSUE TITLE
Fix color contrast of PRIVATE and PUBLIC buttons

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#683]
Red/Green is bad for our colorblind friends.

**Comment by sdellis** [comment]
Perhaps add a distinguishing icon as well?

**Comment by eliotjordan** [comment]
It's better, but `open` and `private` are still awfully close in color to me. Maybe try breaking out of the red / green scheme? Use one of those colors, but not both.

**Comment by jrgriffiniii** [comment]
![figgy_issues_683_screenshot_2](https://user-images.githubusercontent.com/1443986/36315728-62745120-1306-11e8-8fc4-49fc8fc5425e.png)

My sense was that using a brighter (or darker) red in order to indicate that a given resource is openly accessible to all users was simply counterintuitive.  I would argue only slightly in favor for the usage of a green-based scheme given that based it in shades of blue would bring it into conflict with the overall app. scheme.

**Comment by escowles** [comment]
I like using black for private.  But now the open/princeton options are very similar in color.  Could we use orange for princeton-only?

**Comment by jrgriffiniii** [comment]
![figgy_issues_683_screenshot_3](https://user-images.githubusercontent.com/1443986/36318590-49f2587e-130e-11e8-8033-ea457594052a.png)

These are styled in a manner which renders them a bit more similar to buttons rather than canonical Bootstrap Badges, but I was struggling with how else to offset the contrast between the orange and white background.

**Comment by hackmastera** [comment]
this solution looks great @jrgriffiniii!

**Comment by jrgriffiniii** [comment]
Thank you @hackmastera
