### ISSUE TITLE
Bulk edit: workflow status complete, rights statement

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#697]
e.g., complete all items in current search results, or in a collection
requires #1651 
Wireframes copied over from #1651:

Button above search results:
![1651 bulk edit button](https://user-images.githubusercontent.com/845363/44484982-3b108180-a61d-11e8-9c85-0074c9181040.png)

Bulk edit form:
![1651 bulk edit form 1](https://user-images.githubusercontent.com/845363/44484994-44015300-a61d-11e8-9872-10d892a4406c.png)

**Comment by escowles** [comment]
also: bulk set the rights statements at the same time.

**Comment by hackmastera** [comment]
I wonder if we need to adjust the workflows so that "complete" is a universal concept. The draft / publish workflow does not have a "complete" state. If we had a collection with different kinds of resources and they had different workflows, this might be an issue.

I think "published" is a more accurate word than "complete" which is why I used it in draft / publish.

Another thought: I wonder if workflows should be assigned per collection rather than per-model.

**Comment by tpendragon** [comment]
I think someone did some work to identify which workflow step was the end didn't they? That being said, it'd definitely make it easier to talk about if they all had the same end point.

How could it be per collection? Many items have more than one collection, and often don't have a "representative" collection.

**Comment by hackmastera** [comment]
requires #1607

**Comment by escowles** [comment]
Another field that might be a good candidate for bulk edit: ocr_language, to allow bulk-triggering OCR

**Comment by escowles** [comment]
Additional requirements:
* Should require a collection facet to be selected (don't show the button unless a collection is selected?)
* Should have a popup before making updates: "You are going to update X records.  Are you sure?"
