### ISSUE TITLE
Sammelband Support in Order Manager

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#747]
We should be able to manage both files and volumes at the same time in the file manager, in order to support sammelbands, which have covers/frontmatter and multiple child volumes.  Maybe we can simply revert this: https://github.com/pulibrary/figgy/blob/master/valhalla/app/javascript/components/Thumbnails.vue#L16 — but there is additional functionality (like correcting sammelbands ingested as single volumes), so this should probably be part of a larger effort to make that work smoothly.

Child of #247

**Comment by sdellis** [comment]
I agree that we should be able to manage files and volumes in the file manager. I looked into this more closely and there is an unrelated bug that is preventing the "flattened" MVW from displaying. I fixed the bug (PR coming any minute), but it doesn't address some of the other sammelband use cases you outline (i.e., ingested as single volumes, or adding single images to MVWs without flattening). 

This will be part of a larger effort as it will require significant changes on both front and backend. For example, if someone adds filesets a la carte to a MVW, we should generate a manifest that represents a sammelband via the IIIF Presentation spec (using Ranges to represent Volumes instead of Manifests) since that's how the viewers will use it as well. I think that the Filemanager could evolve to manage structure too, which would provide the grouping/splitting functionality needed for these use cases.

**Comment by tpendragon** [comment]
@sdellis A lot of time went into figuring out how to represent Sammelbands. In Plum they do what you're saying - in Figgy the flattening happens, but we just haven't written the range builder.

**Comment by hackmastera** [comment]
In the meantime, should we consider detecting sammelbands and displaying a warning?

**Comment by hackmastera** [comment]
oops, mistakenly autoclosed

**Comment by sdellis** [comment]
Sammelbands currently have a `viewingHint=multi-part` although this is [only valid on Collections](http://prezi3.iiif.io/api/presentation/3.0/#behavior). What is the purpose of setting viewingHint to multi-part here?

**Comment by tpendragon** [comment]
It shouldn't have that viewingHint. Made a new issue: #1565

**Comment by tpendragon** [comment]
Closed - all materials work now since moving to GraphQL.
