### ISSUE TITLE
VUE File Manager should have a way to view a single image enlarged.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#763]
Zooming is great, but if I'm dealing with 1200 files and I'm zoomed out, I can't zoom in to that one file and keep my place.

**Comment by rlskoeser** [comment]
This would be valuable for CDH also.

**Comment by sdellis** [comment]
@rlskoeser In addition to losing one's place, often times the "grow/shrink" feature doesn't provide enough detail either. I'd like to hear your thoughts. One thing I heard is that it's helpful to have the deep zoom and form input visible at the same time. Previously it was in a modal that obstructed the ability to transcribe into the form. In this interface, I assume the use case is for page labels/numbering, but let me know if there's other uses for the zoom I'm not aware of.

**Comment by rlskoeser** [comment]
@sdellis maybe we can set up a time for you to chat with the CDH people who are using the interface more.  Generally I think it is to confirm page labels, but the use case for the Derrida materials is a bit more complicated because we're also labeling the insertions based on a naming convention devised by our faculty PI on the project. I don't know how carefully they have to look at the insertions to figure out how to label them.

**Comment by sdellis** [comment]
That would be fantastic, @rlskoeser. I love to talk to end users! :)

**Comment by rlskoeser** [comment]
When you change the zoom level, it would be much more useful if the current images in view stay in view.  Maybe the images at the top of the viewer window should stay at the top?  If that's too hard, at least if I have an image selected it should stay in view.
