### ISSUE TITLE
IIIF metadata workflow and performance

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#836]
Can we simplify the generation of metadata, manifests, indexing, etc. between Figgy, Bibdata and Orangelight?

* Should Bibdata be generating the display metadata instead of Figgy?
* Should we be caching the manifests in OL to reduce runtime dependency on Figgy?
* Should we be reindexing OL records in realtime when there are updates in Figgy?
* etc.

**Comment by jrgriffiniii** [comment]
> Should we be reindexing OL records in realtime when there are updates in Figgy?
I strongly agree with this (otherwise Bibdata must synchronously update its ARK caches in order to determine whether or not Figgy or Plum will hold a given Manifest, or which Figgy resource current has a given manifest for any ARK...)
> Should we be caching the manifests in OL to reduce runtime dependency on Figgy?
If this is supported using RabbitMQ, then a HTTP request wouldn't be required to provide this when it is reindexed from Bibdata

**Comment by escowles** [comment]
The first bullet (bibdata generating display forms for both Figgy and OL) was mostly motivated by having data in OL and the manifest be different.  @tpendragon notes that could just be because the Figgy data was stale (which would be fixed by #696).  It could also be because the JSON-LD is pulling the wrong forms of data from the solr document, so adjusting the JSON-LD generation could fix that.

**Comment by tpendragon** [comment]
`Should Bibdata be generating the display metadata instead of Figgy?`

Bibdata generates the JSON-LD which is used, except for maybe a couple properties which are specific to Figgy. Figgy also refreshes its metadata when it changes upstream. I think this is done.

`Should we be caching the manifests in OL to reduce runtime dependency on Figgy?`
Orangelight queries Figgy so we don't have to keep writing to the OL solr index - I think we've decided that's a good thing.

`Should we be reindexing OL records in realtime when there are updates in Figgy?`

Orangelight now queries Figgy for manifests, so we shouldn't have to reindex OL in realtime with Figgy updates.

I propose we close this. Yes @escowles?

**Comment by escowles** [comment]
Yes, I think we've gone back to the display-time query approach, so most of these questions aren't valid any more.
